import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  emptyState: {
    minHeight: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    gap: 8,
  },
  emptyStateText: {
    color: '#837f7c',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 18, 16, 0.46)',
    justifyContent: 'flex-end',
  },
  modalKeyboardAvoidingView: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  createLeadModal: {
    maxHeight: '86%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#fcfaf8',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    marginBottom: 14,
  },
  modalTitle: {
    color: '#264721',
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '700',
  },
  modalSubtitle: {
    marginTop: 3,
    color: '#837f7c',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  modalCloseButton: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  modalCloseText: {
    color: '#0f362b',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  formField: {
    marginBottom: 11,
  },
  formLabel: {
    marginBottom: 5,
    color: '#3d5a40',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  formInput: {
    minHeight: 43,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    color: '#19191f',
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  dateSelectButton: {
    minHeight: 43,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
  },
  dateSelectText: {
    color: '#19191f',
    fontSize: 14,
    fontWeight: '600',
  },
  dateSelectPlaceholder: {
    color: '#9a9188',
    fontWeight: '400',
  },
  formOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  formOptionButton: {
    flexBasis: '30%',
    flexGrow: 1,
    minWidth: 0,
    minHeight: 39,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  formOptionButtonActive: {
    borderColor: '#54bda2',
    backgroundColor: '#0d3329',
  },
  formOptionText: {
    color: '#3d3b3b',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
  },
  formOptionTextActive: {
    color: '#ffffff',
  },
  propertySelectButton: {
    minHeight: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  propertySelectCopy: {
    flex: 1,
    minWidth: 0,
  },
  propertySelectTitle: {
    color: '#19191f',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  propertySelectMeta: {
    marginTop: 2,
    color: '#837f7c',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '500',
  },
  propertySearchRow: {
    height: 39,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 11,
    marginBottom: 12,
  },
  propertySearchInput: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 14,
    padding: 0,
  },
  propertyPickerList: {
    gap: 10,
    paddingBottom: 4,
  },
  propertyPickerCard: {
    minHeight: 96,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 9,
  },
  propertyPickerCardSelected: {
    borderColor: '#0f362b',
    backgroundColor: '#f3f7ef',
  },
  propertyPickerImage: {
    width: 74,
    height: 74,
    borderRadius: 11,
    backgroundColor: '#edf1e0',
  },
  propertyPickerImagePlaceholder: {
    width: 74,
    height: 74,
    borderRadius: 11,
    backgroundColor: '#edf1e0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyPickerImageText: {
    color: '#264721',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
  },
  propertyPickerBody: {
    flex: 1,
    minWidth: 0,
  },
  propertyPickerTitle: {
    color: '#000000',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '800',
  },
  propertyPickerAddress: {
    marginTop: 3,
    color: '#af8c49',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  propertyPickerMetaRow: {
    marginTop: 8,
    gap: 3,
  },
  propertyPickerPrice: {
    color: '#0f362b',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
  },
  propertyPickerPill: {
    minWidth: 56,
    minHeight: 25,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#fcfaf8',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  propertyPickerPillSelected: {
    borderColor: '#0f362b',
    backgroundColor: '#0f362b',
  },
  propertyPickerPillText: {
    color: '#0f362b',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
  },
  propertyPickerPillTextSelected: {
    color: '#ffffff',
  },
  modalErrorText: {
    marginTop: 2,
    marginBottom: 10,
    color: '#ba544a',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  createLeadButton: {
    minHeight: 44,
    borderRadius: 22,
    backgroundColor: '#0f362b',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginTop: 4,
  },
  createLeadButtonDisabled: {
    backgroundColor: '#8d8783',
  },
  createLeadButtonText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
  },
  
})
