import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  alertRow: {
    minHeight: 28,
    marginTop: -1,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#999595',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 9,
  },
  alertText: {
    flex: 1,
    minWidth: 0,
    color: '#ba544a',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '600',
  },
  leadCard: {
    minHeight: 104,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    padding: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  leadTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  leadAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#edf1e0',
  },
  leadMain: {
    flex: 1,
    minWidth: 0,
  },
  leadName: {
    color: '#000000',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  leadProperty: {
    color: '#af8c49',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  sourceRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sourceText: {
    color: '#000000',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  statusStack: {
    alignItems: 'flex-end',
    gap: 5,
  },
  statusPill: {
    minWidth: 102,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bdbdbd',
    backgroundColor: '#edf1e0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 8,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#3e534e',
  },
  advisorStatusPill: {
    backgroundColor: '#fff9eb',
    borderColor: '#e8c986',
  },
  advisorStatusDot: {
    backgroundColor: '#c78d1c',
  },
  advisorStatusText: {
    color: '#8a5d13',
  },
  statusText: {
    color: '#3e534e',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  leadFooter: {
    marginTop: 9,
    minHeight: 31,
    borderTopWidth: 0.5,
    borderTopColor: '#e4dfd9',
    flexDirection: 'row',
    alignItems: 'center',
  },
  footerCell: {
    flex: 1,
    minWidth: 0,
    paddingTop: 8,
    paddingRight: 8,
  },
  footerCellMiddle: {
    borderLeftWidth: 0.5,
    borderLeftColor: '#e4dfd9',
    paddingLeft: 9,
  },
  footerLabel: {
    color: '#000000',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  footerValue: {
    marginTop: 2,
    color: '#000000',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  followButton: {
    minWidth: 92,
    height: 28,
    borderLeftWidth: 0.5,
    borderLeftColor: '#e4dfd9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 2,
    paddingTop: 8,
  },
  followButtonText: {
    color: '#000000',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  notionIcon: {
    width: 18,
    height: 18,
    borderRadius: 3,
    backgroundColor: '#191919',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notionIconText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '800',
  },
  
})
