import { Platform, StyleSheet } from 'react-native'
import { generalColors } from '@/theme'
const numberFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'serif',
})

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: generalColors.background,
  },
  content: {
    paddingHorizontal: 11,
    paddingTop: 42,
    paddingBottom: 96,
  },
  logoWrap: {
    alignItems: 'center',
    marginBottom: 12,
  },
  topRow: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  roleLabel: {
    color: '#315b41',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 6,
  },
  datePill: {
    height: 18,
    borderRadius: 5,
    backgroundColor: '#c9af6f',
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '600',
  },
  profileRow: {
    marginTop: -14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 5,
  },
  profileLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    position: 'relative',
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 28,
    backgroundColor: '#d8ba78',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarText: {
    color: '#24442f',
    fontSize: 16,
    fontWeight: '800',
  },
  greeting: {
    color: '#232323',
    fontFamily: "cormorant",
    fontSize: 25,
    lineHeight: 30,
  },
  helper: {
    color: '#8d8d8d',
    fontSize: 12,
    lineHeight: 16,
  },
  notification: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  heroCards: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 5,
  },
  earningsCard: {
    flex: 1,
    height: 104,
    borderRadius: 10,
    backgroundColor: '#f9f3ef',
    borderWidth: 1,
    borderColor: '#e0d5cf',
    paddingTop: 5,
    paddingHorizontal: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
    gap: 4,
  },
  earningsLabel: {
    color: '#bf7634',
    fontSize: 12,
    textAlign: 'center',
    letterSpacing: 1.3,
  },
  earningsValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  earningsValue: {
    color: '#20252b',
    fontFamily: numberFont,
    fontSize: 39,
    lineHeight: 43,
  },
  currency: {
    color: '#20252b',
    fontSize: 12,
    marginBottom: 9,
    marginLeft: 4,
  },
  earningsCaption: {
    color: '#8a817e',
    fontSize: 13,
    textAlign: 'center',
    marginTop: -2,
  },
  sectionHeader: {
    marginTop: 3,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-between'
  },
  sectionHeaderTitle: {
    color: '#006b43',
    fontSize: 15,
    fontWeight: '700',
  },
  sectionAction: {
    color: '#006b43',
    fontSize: 12,
    fontWeight: '700',
  },
  panel: {
    borderRadius: 9,
    backgroundColor: '#fffdfc',
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.16,
    shadowRadius: 5,
    elevation: 4,
  },
  appointmentsPanel: {
    paddingBottom: 12,
    marginTop: 12,
  },
  appointmentsScroll: {
    maxHeight: 296,
  },
  appointmentList: {
    gap: 4,
  },
  centerButton: {
    alignSelf: 'center',
    marginTop: 10,
    height: 33,
    flex: 1,
    minWidth: 0,
    borderRadius: 5,
    backgroundColor: '#c89c4c',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
  },
  centerButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  appointmentActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  leadPanel: {
    marginTop: 12,
  },
  panelSubtitle: {
    color: '#7b8780',
    fontSize: 10,
    marginBottom: 5
  },
  metricGrid: {
    flexDirection: 'row',
    gap: 6,
  },
  subTitle: {
    color: '#006b43',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 7,
  },
  funnelRow: {
    minHeight: 72,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e4e4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 6,
  },
  outlineButton: {
    alignSelf: 'center',
    marginTop: 14,
    height: 32,
    minWidth: 127,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dcdcdc',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
  },
  outlineButtonText: {
    color: '#006b43',
    fontSize: 12,
    fontWeight: '700',
  },
})
