import { StyleSheet } from "react-native";
import { generalColors } from "@/theme";
const LARGE_NUMBER_FONT = "Castoro Titling";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: generalColors.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: 11,
    //paddingTop: 42,
    paddingTop: 50,
    gap: 9,
  },
  detailContainer: {
    paddingHorizontal: 0,
    paddingBottom: 0,
    gap: 0,
  },
  content: {
    paddingBottom: 130,
  },
  brandBlock: {
    height: 60,
    alignItems: "center",
    justifyContent: "center",
  },

  headerRow: {
    marginTop: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#f3eee6",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#e3d7c8",
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: "#3d5a40",
    fontSize: 24,
    lineHeight: 29,
    fontWeight: "600",
  },
  subtitle: {
    marginTop: 2,
    color: "#8d8783",
    fontSize: 13,
    lineHeight: 17,
  },
  metricRow: {
    marginTop: 24,
    flexDirection: "row",
    gap: 10,
  },
  metricCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 102,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#b8b4b0",
    backgroundColor: "#fcfaf8",
    paddingHorizontal: 8,
    paddingVertical: 9,
    justifyContent: "space-between",
  },
  metricDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  metricValue: {
    color: "#000000",
    fontFamily: LARGE_NUMBER_FONT,
    fontSize: 30,
    lineHeight: 38,
  },
  metricLabel: {
    color: "#000000",
    fontSize: 9,
    lineHeight: 13,
    fontWeight: "600",
  },
  searchRow: {
    marginTop: 16,
    height: 31,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#c0c0c0",
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 10,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: "#2c2c2c",
    fontSize: 14,
    padding: 0,
  },
  filterRow: {
    marginTop: 9,
    flexDirection: "row",
    gap: 8,
  },
  filterChip: {
    flex: 1,
    minWidth: 0,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#c8c8c8",
    backgroundColor: "#fcfaf7",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  filterChipActive: {
    backgroundColor: "#0d3329",
    borderColor: "#54bda2",
  },
  filterText: {
    color: "#837f7c",
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "500",
  },
  filterTextActive: {
    color: "#ffffff",
  },
  sectionTitle: {
    marginTop: 15,
    marginBottom: 8,
    color: "#000000",
    fontSize: 22,
    lineHeight: 27,
    fontWeight: "600",
  },
  alertList: {
    gap: 0,
    paddingHorizontal: 9,
  },
  leadList: {
    gap: 10,
    paddingHorizontal: 10,
  },
  emptyState: {
    minHeight: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e3e0e0",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    gap: 8,
  },
  emptyStateText: {
    color: "#837f7c",
    fontSize: 13,
    lineHeight: 18,
    textAlign: "center",
  },
  paginationActions: {
    marginTop: 12,
    paddingHorizontal: 10,
    flexDirection: "row",
    gap: 10,
  },
  paginationButton: {
    flex: 1,
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "#0f362b",
    backgroundColor: "#0f362b",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  paginationButtonDisabled: {
    borderColor: "#d4ccc3",
    backgroundColor: "#f0ece7",
  },
  paginationButtonText: {
    color: "#ffffff",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "700",
  },
  paginationButtonTextDisabled: {
    color: "#9a9188",
  },
  assistantDock: {
    position: "absolute",
    right: 8,
    bottom: 76,
    width: 226,
    alignItems: "stretch",
    zIndex: 30,
  },
  assistantMenu: {
    width: 220,
    alignSelf: "flex-start",
    marginBottom: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#dabc8d",
    backgroundColor: "#ffffff",
    overflow: "hidden",
  },
  assistantAction: {
    minHeight: 31,
    borderBottomWidth: 0.5,
    borderBottomColor: "#c8c0b9",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
  },
  assistantActionLast: {
    borderBottomWidth: 0,
  },
  assistantActionText: {
    flex: 1,
    minWidth: 0,
    color: "#363739",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
  },
  assistantButtonRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
  },
  assistantButton: {
    flex: 1,
    height: 36,
    borderRadius: 999,
    backgroundColor: "#0f362b",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  assistantButtonText: {
    color: "#ffffff",
    fontSize: 12,
    lineHeight: 15,
    fontWeight: "600",
  },
});
