import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 68,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 6,
    borderTopWidth: 1,
    borderTopColor: '#eee7dc',
  },
  navItem: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    height: 54,
  },
  navItemActive: {
    flex: 1,
    minWidth: 0,
    height: 68,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: -8,
  },
  navLabel: {
    color: '#3d3d3d',
    fontSize: 8,
    lineHeight: 10,
    marginTop: 3,
    textAlign: 'center',
  },
  navActiveScoop: {
    position: 'absolute',
    top: -1,
    width: 74,
    height: 62,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
    backgroundColor: '#c2a661bb',
  },
  navActiveButton: {
    paddingTop: 16,
  },
  badge: {
    position: 'absolute',
    top: 2,
    right: 17,
    zIndex: 2,
    minWidth: 16,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#42e748',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  badgeText: {
    color: '#0b3b22',
    fontSize: 8,
    lineHeight: 10,
  },
})
