import { Platform, StyleSheet } from 'react-native'

const serifFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'serif',
})

export const registerOwnerStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fefbf6',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 56,
    paddingTop: 57,
    paddingBottom: 40,
  },
  leftArchBack: {
    position: 'absolute',
    left: -46,
    top: 54,
    width: 69,
    height: 353,
    borderTopRightRadius: 116,
    borderWidth: 4,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderColor: 'rgba(215,182,149,0.41)',
    backgroundColor: '#ffffff',
    shadowColor: '#d7b695',
    shadowOffset: { width: 2, height: 9 },
    shadowOpacity: 0.25,
    shadowRadius: 40,
    elevation: 4,
  },
  leftArchFront: {
    position: 'absolute',
    left: -12,
    top: 34,
    width: 73,
    height: 373,
    borderTopRightRadius: 116,
    borderWidth: 4,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    borderColor: 'rgba(215,182,149,0.41)',
    backgroundColor: '#ffffff',
    shadowColor: '#d7b695',
    shadowOffset: { width: 2, height: 9 },
    shadowOpacity: 0.25,
    shadowRadius: 40,
    elevation: 3,
  },
  topRing: {
    position: 'absolute',
    right: -81,
    top: -92,
    width: 150,
    height: 251,
    borderWidth: 2,
    borderColor: '#c7895e',
    borderRadius: 80,
    transform: [{ rotate: '-7deg' }],
  },
  plantImage: {
    position: 'absolute',
    left: -1,
    top: 176,
    width: 90,
    height: 237,
  },
  logoWrap: {
    alignItems: 'center',
    marginTop: 19,
    marginBottom: 45,
  },
  titleBlock: {
    width: 238,
    alignItems: 'center',
  },
  title: {
    color: '#1b382c',
    fontFamily: serifFont,
    fontSize: 30,
    fontWeight: '400',
    lineHeight: 36,
    textAlign: 'center',
  },
  copyGroup: {
    width: 238,
    alignItems: 'center',
    gap: 14,
    marginTop: 14,
  },
  description: {
    color: '#5c5e5d',
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: 0.98,
    textAlign: 'center',
  },
  exclusiveCard: {
    width: '100%',
    maxWidth: 318,
    minHeight: 134,
    marginTop: 150,
    borderWidth: 2,
    borderColor: '#ffe7ca',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  exclusiveContent: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  iconCircle: {
    width: 76,
    height: 77,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f7f0e8',
  },
  lockImage: {
    width: 44,
    height: 57,
  },
  exclusiveCopy: {
    flex: 1,
    gap: 8,
  },
  exclusiveTitle: {
    color: '#01402f',
    fontFamily: serifFont,
    fontSize: 24,
    fontWeight: '400',
    lineHeight: 25,
  },
  exclusiveText: {
    color: '#000000',
    fontSize: 13,
    lineHeight: 17,
    letterSpacing: 0.52,
  },
  actions: {
    width: '100%',
    maxWidth: 328,
    gap: 10,
    marginTop: 29,
    paddingHorizontal: 10,
  },
  primaryButton: {
    width: '100%',
    height: 45,
    borderRadius: 12,
    backgroundColor: '#013f2f',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 25,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 15,
    lineHeight: 16,
  },
  secondaryButton: {
    width: '100%',
    height: 45,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#013f2f',
    fontSize: 15,
    lineHeight: 16,
    textAlign: 'center',
  },
})

