import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#ffffff' },
  screen: { flex: 1, backgroundColor: '#ffffff' },
  backButton: {
    position: 'absolute',
    left: 14,
    top: 14,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f3eee6',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 4,
  },
  brandBlock: { alignItems: 'center', marginTop: 12 },
  brandTitle: { color: '#284629', fontSize: 28, lineHeight: 34, fontWeight: '500', letterSpacing: 6 },
  brandSubtitle: { color: '#d19a5b', fontSize: 11, lineHeight: 14, letterSpacing: 4 },
  titleBlock: { marginTop: 14, paddingHorizontal: 14 },
  title: { color: '#19191f', fontSize: 22, lineHeight: 27, fontWeight: '700' },
  subtitle: { marginTop: 3, color: '#8d8d96', fontSize: 13, lineHeight: 17, fontWeight: '600' },
  filterScroll: { flexGrow: 0, marginTop: 14},
  filterContent: { paddingHorizontal: 17, gap: 8 },
  filterChip: {
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 13,
  },
  keyboardView: {
    flex: 1,
  },
  filterChipActive: { 
    backgroundColor: '#004638', 
    borderColor: '#004638' 
  },
  filterChipWarm: { 
    borderColor: '#d69534' 
  },
  filterText: { color: '#12382f', fontSize: 13, lineHeight: 17, fontWeight: '700' },
  filterTextActive: { color: '#ffffff' },
  filterTextWarm: { color: '#c98412' },
  timelineContent: { marginTop: 1, paddingTop: 12, paddingBottom: 112 },
  timelineRail: { position: 'absolute', top: 25, bottom: 0, left: 55, width: 1, backgroundColor: '#cfd3cf' },
  timelineRow: { flexDirection: 'row', minHeight: 108, paddingLeft: 18, paddingRight: 12 },
  timelineRowLast: { minHeight: 96 },
  dotColumn: { width: 58, alignItems: 'center' },
  smallDot: {
    position: 'absolute',
    left: 1,
    top: 18,
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#064b38',
    backgroundColor: '#ffffff',
    zIndex: 2,
  },
  iconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#073f34',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 3,
    zIndex: 3,
  },
  followingCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d1d1',
    backgroundColor: '#ffffff',
    padding: 10,
    marginBottom: 7,
  },
  followingHeader: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  timeRow: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  dateText: { color: '#0c6740', fontSize: 11, lineHeight: 14, fontWeight: '600' },
  timeText: { color: '#0c6740', fontSize: 11, lineHeight: 14, fontWeight: '500' },
  tagPill: {
    minHeight: 22,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#cbd8c3',
    backgroundColor: '#f5fbef',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  tagText: { color: '#0c6740', fontSize: 10, lineHeight: 13, fontWeight: '600' },
  messageBubble: {
    minHeight: 46,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#cfcfcf',
    backgroundColor: '#fbfbfb',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 6,
  },
  followingText: { color: '#19191f', fontSize: 12, lineHeight: 16 },
  attachmentGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  attachmentThumbButton: {
    width: 112,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  attachmentThumb: {
    width: '100%',
    height: 82,
    backgroundColor: '#edf1e0',
  },
  attachmentThumbPlaceholder: {
    width: '100%',
    height: 82,
    backgroundColor: '#edf1e0',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  attachmentThumbPlaceholderText: {
    color: '#6f786f',
    fontSize: 10,
    lineHeight: 13,
    textAlign: 'center',
  },
  attachmentMeta: {
    minHeight: 30,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 7,
    paddingVertical: 6,
  },
  attachmentName: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  emptyTimeline: {
    minHeight: 420,
    marginLeft: 81,
    marginRight: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d1d1d1',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingVertical: 28,
  },
  emptyIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#edf1e0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  emptyTitle: { color: '#19191f', fontSize: 16, lineHeight: 20, fontWeight: '700', textAlign: 'center' },
  emptyText: { marginTop: 7, color: '#717171', fontSize: 12, lineHeight: 17, textAlign: 'center' },
  bottomDock: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 8,
  },
  quickActionsRow: { flexDirection: 'row', gap: 5 },
  bottomPill: {
    flex: 1,
    minWidth: 0,
    height: 33,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 5,
  },
  bottomPillDark: { backgroundColor: '#064b38', borderColor: '#064b38' },
  bottomPillText: { color: '#19191f', fontSize: 9, lineHeight: 12, fontWeight: '700' },
  bottomPillTextDark: { color: '#ffffff' },
  addActivityButton: {
    height: 36,
    borderRadius: 10,
    backgroundColor: '#064b38',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    marginTop: 6,
  },
  addActivityText: { color: '#ffffff', fontSize: 12, lineHeight: 15, fontWeight: '700' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.24)',
    justifyContent: 'flex-end',
  },
  imagePreviewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.88)',
    paddingHorizontal: 14,
    paddingTop: 46,
    paddingBottom: 28,
  },
  imagePreviewHeader: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  imagePreviewTitle: {
    flex: 1,
    minWidth: 0,
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  imagePreviewCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePreview: {
    flex: 1,
    width: '100%',
  },
  activityModal: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  modalTitle: {
    color: '#19191f',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '700',
  },
  modalSubtitle: {
    marginTop: 3,
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3eee6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputLabel: {
    marginTop: 18,
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  activityInput: {
    minHeight: 112,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#fbfbfb',
    color: '#19191f',
    fontSize: 13,
    lineHeight: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 7,
  },
  imagePickerButton: {
    minHeight: 58,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 12,
  },
  imagePickerCopy: {
    flex: 1,
    minWidth: 0,
  },
  imagePickerTitle: {
    color: '#19191f',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
  },
  imagePickerMeta: {
    marginTop: 2,
    color: '#717171',
    fontSize: 11,
    lineHeight: 15,
  },
  removeImageButton: {
    alignSelf: 'flex-start',
    minHeight: 28,
    justifyContent: 'center',
    marginTop: 6,
  },
  removeImageText: {
    color: '#a13b2f',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  modalErrorText: {
    color: '#a13b2f',
    fontSize: 12,
    lineHeight: 16,
    marginTop: 10,
  },
  saveActivityButton: {
    height: 42,
    borderRadius: 12,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
  },
  saveActivityButtonDisabled: {
    opacity: 0.65,
  },
  saveActivityText: {
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
  },
})
