import { StyleSheet } from 'react-native'

const LARGE_NUMBER_FONT = 'Castoro Titling'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fcfaf8',
  },
  container: {
    flex: 1,
  },
  detailContainer: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 28,
    paddingBottom: 16,
  },
  content: {
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 112,
  },
  brandBlock: {
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandTitle: {
    color: '#264721',
    fontSize: 29,
    lineHeight: 34,
    fontWeight: '600',
    letterSpacing: 8,
  },
  brandSubtitle: {
    color: '#bf8638',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '500',
    letterSpacing: 2.3,
  },
  headerRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f3eee6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e3d7c8',
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 18,
  },
  detailHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  detailContent: {
    paddingBottom: 40,
  },
  detailLeadCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingVertical: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 7,
    elevation: 3,
  },
  detailLeadAvatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#edf1e0',
  },
  detailLeadName: {
    marginTop: 12,
    color: '#000000',
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '800',
    textAlign: 'center',
  },
  detailLeadProperty: {
    marginTop: 4,
    color: '#af8c49',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  detailStatusPill: {
    marginTop: 12,
    minHeight: 25,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#bdbdbd',
    backgroundColor: '#edf1e0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 12,
  },
  detailInfoCard: {
    marginTop: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  detailInfoRow: {
    minHeight: 44,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e4dfd9',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 9,
  },
  detailInfoLabel: {
    width: 112,
    color: '#837f7c',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  detailInfoValue: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: '#3d5a40',
    fontSize: 24,
    lineHeight: 29,
    fontWeight: '600',
  },
  subtitle: {
    marginTop: 2,
    color: '#8d8783',
    fontSize: 13,
    lineHeight: 17,
  },
  metricRow: {
    marginTop: 24,
    flexDirection: 'row',
    gap: 10,
  },
  metricCard: {
    flex: 1,
    minWidth: 0,
    minHeight: 102,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#b8b4b0',
    backgroundColor: '#fcfaf8',
    paddingHorizontal: 8,
    paddingVertical: 9,
    justifyContent: 'space-between',
  },
  metricDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  metricValue: {
    color: '#000000',
    fontFamily: LARGE_NUMBER_FONT,
    fontSize: 30,
    lineHeight: 38,
  },
  metricLabel: {
    color: '#000000',
    fontSize: 9,
    lineHeight: 13,
    fontWeight: '600',
  },
  searchRow: {
    marginTop: 16,
    height: 31,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#c0c0c0',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 10,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: '#2c2c2c',
    fontSize: 14,
    padding: 0,
  },
  filterRow: {
    marginTop: 9,
    flexDirection: 'row',
    gap: 8,
  },
  filterChip: {
    flex: 1,
    minWidth: 0,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#c8c8c8',
    backgroundColor: '#fcfaf7',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  filterChipActive: {
    backgroundColor: '#0d3329',
    borderColor: '#54bda2',
  },
  filterText: {
    color: '#837f7c',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '500',
  },
  filterTextActive: {
    color: '#ffffff',
  },
  sectionTitle: {
    marginTop: 15,
    marginBottom: 8,
    color: '#000000',
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '600',
  },
  alertList: {
    gap: 0,
    paddingHorizontal: 9,
  },
  alertRow: {
    minHeight: 28,
    marginTop: -1,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#999595',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    gap: 9,
  },
  alertText: {
    flex: 1,
    minWidth: 0,
    color: '#ba544a',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '600',
  },
  leadList: {
    gap: 10,
    paddingHorizontal: 10,
  },
  leadCard: {
    minHeight: 104,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    padding: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  leadTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  leadAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#edf1e0',
  },
  leadMain: {
    flex: 1,
    minWidth: 0,
  },
  leadName: {
    color: '#000000',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  leadProperty: {
    color: '#af8c49',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  sourceRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sourceText: {
    color: '#000000',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  statusStack: {
    alignItems: 'flex-end',
    gap: 5,
  },
  statusPill: {
    minWidth: 102,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bdbdbd',
    backgroundColor: '#edf1e0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 8,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#3e534e',
  },
  advisorStatusPill: {
    backgroundColor: '#fff9eb',
    borderColor: '#e8c986',
  },
  advisorStatusDot: {
    backgroundColor: '#c78d1c',
  },
  advisorStatusText: {
    color: '#8a5d13',
  },
  statusText: {
    color: '#3e534e',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  leadFooter: {
    marginTop: 9,
    minHeight: 31,
    borderTopWidth: 0.5,
    borderTopColor: '#e4dfd9',
    flexDirection: 'row',
    alignItems: 'center',
  },
  footerCell: {
    flex: 1,
    minWidth: 0,
    paddingTop: 8,
    paddingRight: 8,
  },
  footerCellMiddle: {
    borderLeftWidth: 0.5,
    borderLeftColor: '#e4dfd9',
    paddingLeft: 9,
  },
  footerLabel: {
    color: '#000000',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  footerValue: {
    marginTop: 2,
    color: '#000000',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  followButton: {
    minWidth: 92,
    height: 28,
    borderLeftWidth: 0.5,
    borderLeftColor: '#e4dfd9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 2,
    paddingTop: 8,
  },
  followButtonText: {
    color: '#000000',
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '600',
  },
  emptyState: {
    minHeight: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    gap: 8,
  },
  emptyStateText: {
    color: '#837f7c',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  paginationHeader: {
    marginBottom: 9,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  paginationText: {
    color: '#6f6862',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '600',
  },
  paginationActions: {
    marginTop: 12,
    paddingHorizontal: 10,
    flexDirection: 'row',
    gap: 10,
  },
  paginationButton: {
    flex: 1,
    minHeight: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#0f362b',
    backgroundColor: '#0f362b',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  paginationButtonDisabled: {
    borderColor: '#d4ccc3',
    backgroundColor: '#f0ece7',
  },
  paginationButtonText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  paginationButtonTextDisabled: {
    color: '#9a9188',
  },
  assistantDock: {
    position: 'absolute',
    right: 8,
    bottom: 76,
    width: 226,
    alignItems: 'stretch',
    zIndex: 30,
  },
  assistantMenu: {
    width: 220,
    alignSelf: 'flex-start',
    marginBottom: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#dabc8d',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  assistantAction: {
    minHeight: 31,
    borderBottomWidth: 0.5,
    borderBottomColor: '#c8c0b9',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  assistantActionLast: {
    borderBottomWidth: 0,
  },
  assistantActionText: {
    flex: 1,
    minWidth: 0,
    color: '#363739',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '600',
  },
  assistantButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 10,
  },
  assistantButton: {
    flex: 1,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0f362b',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  assistantButtonText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '600',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(15, 18, 16, 0.46)',
    justifyContent: 'flex-end',
  },
  modalKeyboardAvoidingView: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  createLeadModal: {
    maxHeight: '86%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#fcfaf8',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 28,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
    marginBottom: 14,
  },
  modalTitle: {
    color: '#264721',
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '700',
  },
  modalSubtitle: {
    marginTop: 3,
    color: '#837f7c',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
  },
  modalCloseButton: {
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  modalCloseText: {
    color: '#0f362b',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  formField: {
    marginBottom: 11,
  },
  formLabel: {
    marginBottom: 5,
    color: '#3d5a40',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  formInput: {
    minHeight: 43,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    color: '#19191f',
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  formOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  formOptionButton: {
    minWidth: '47%',
    minHeight: 39,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  formOptionButtonActive: {
    borderColor: '#54bda2',
    backgroundColor: '#0d3329',
  },
  formOptionText: {
    color: '#3d3b3b',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
  },
  formOptionTextActive: {
    color: '#ffffff',
  },
  propertySelectButton: {
    minHeight: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  propertySelectCopy: {
    flex: 1,
    minWidth: 0,
  },
  propertySelectTitle: {
    color: '#19191f',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  propertySelectMeta: {
    marginTop: 2,
    color: '#837f7c',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '500',
  },
  propertySearchRow: {
    height: 39,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 11,
    marginBottom: 12,
  },
  propertySearchInput: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 14,
    padding: 0,
  },
  propertyPickerList: {
    gap: 10,
    paddingBottom: 4,
  },
  propertyPickerCard: {
    minHeight: 96,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e3e0e0',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 9,
  },
  propertyPickerCardSelected: {
    borderColor: '#0f362b',
    backgroundColor: '#f3f7ef',
  },
  propertyPickerImage: {
    width: 74,
    height: 74,
    borderRadius: 11,
    backgroundColor: '#edf1e0',
  },
  propertyPickerImagePlaceholder: {
    width: 74,
    height: 74,
    borderRadius: 11,
    backgroundColor: '#edf1e0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  propertyPickerImageText: {
    color: '#264721',
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
  },
  propertyPickerBody: {
    flex: 1,
    minWidth: 0,
  },
  propertyPickerTitle: {
    color: '#000000',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '800',
  },
  propertyPickerAddress: {
    marginTop: 3,
    color: '#af8c49',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  propertyPickerMetaRow: {
    marginTop: 8,
    gap: 3,
  },
  propertyPickerPrice: {
    color: '#0f362b',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
  },
  propertyPickerId: {
    color: '#837f7c',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  propertyPickerPill: {
    minWidth: 56,
    minHeight: 25,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#d4ccc3',
    backgroundColor: '#fcfaf8',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  propertyPickerPillSelected: {
    borderColor: '#0f362b',
    backgroundColor: '#0f362b',
  },
  propertyPickerPillText: {
    color: '#0f362b',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
  },
  propertyPickerPillTextSelected: {
    color: '#ffffff',
  },
  modalErrorText: {
    marginTop: 2,
    marginBottom: 10,
    color: '#ba544a',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
  },
  createLeadButton: {
    minHeight: 44,
    borderRadius: 22,
    backgroundColor: '#0f362b',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginTop: 4,
  },
  createLeadButtonDisabled: {
    backgroundColor: '#8d8783',
  },
  createLeadButtonText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
  },
})
