import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  container: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 28,
    paddingBottom: 78,
  },
  subScreenContainer: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 28,
    paddingBottom: 16,
  },
  title: {
    color: '#3D5A40',
    fontSize: 26,
    lineHeight: 31,
    fontWeight: '600',
  },
  subtitle: {
    marginTop: 4,
    color: '#717171',
    fontSize: 13,
    lineHeight: 18,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
  },
  summaryTile: {
    flex: 1,
    minWidth: 0,
    height: 64,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#e1d8cb',
    backgroundColor: '#fbf8f2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryValue: {
    color: '#0c6740',
    fontSize: 19,
    lineHeight: 23,
    fontWeight: '700',
  },
  summaryLabel: {
    marginTop: 2,
    color: '#717171',
    fontSize: 10,
    lineHeight: 13,
  },
  searchRow: {
    height: 43,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#d6cec3',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    marginTop: 14,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 13,
    padding: 0,
  },
  errorBox: {
    marginTop: 12,
    borderRadius: 8,
    backgroundColor: '#fff0ee',
    padding: 11,
  },
  errorText: {
    color: '#a13b2f',
    fontSize: 12,
    lineHeight: 16,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: {
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  listContent: {
    paddingTop: 14,
    paddingBottom: 28,
  },
  screenHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f3eee6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  advisorCard: {
    minHeight: 82,
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  advisorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
  },
  advisorAvatarText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  advisorCardBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 11,
  },
  advisorContact: {
    marginTop: 3,
    color: '#9a9084',
    fontSize: 11,
    lineHeight: 14,
  },
  advisorHeader: {
    minHeight: 54,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#e1d8cb',
    backgroundColor: '#fbf8f2',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    marginBottom: 9,
  },
  advisorHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  advisorName: {
    color: '#3D5A40',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '700',
  },
  advisorMeta: {
    marginTop: 3,
    color: '#717171',
    fontSize: 11,
    lineHeight: 14,
  },
  advisorCountBadge: {
    minWidth: 34,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  advisorCountText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  leadSeparator: {
    height: 9,
  },
  sectionSeparator: {
    height: 16,
  },
  separator: {
    height: 9,
  },
  leadCard: {
    minHeight: 82,
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  leadAvatar: {
    width: 42,
    height: 42,
    borderRadius: 9,
    backgroundColor: '#f1eadf',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leadAvatarText: {
    color: '#0c6740',
    fontSize: 17,
    fontWeight: '700',
  },
  leadBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 11,
  },
  leadName: {
    color: '#19191f',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '600',
  },
  leadMeta: {
    marginTop: 3,
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 14,
  },
  leadProperty: {
    marginTop: 3,
    color: '#717171',
    fontSize: 11,
    lineHeight: 14,
  },
  leadDetailCard: {
    minHeight: 70,
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#fbf8f2',
    justifyContent: 'center',
    paddingHorizontal: 12,
    marginTop: 14,
  },
  leadDetailTitle: {
    color: '#3D5A40',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  leadDetailMeta: {
    marginTop: 4,
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  emptyState: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  emptyStateText: {
    color: '#717171',
    fontSize: 13,
    lineHeight: 25,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.22)',
    justifyContent: 'flex-end',
  },
  followPanel: {
    maxHeight: '78%',
    minHeight: 360,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  modalTitle: {
    color: '#19191f',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '700',
  },
  modalSubtitle: {
    marginTop: 3,
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3eee6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followLoadingState: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  followErrorText: {
    marginTop: 24,
    color: '#a13b2f',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  emptyFollowState: {
    minHeight: 240,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  followListContent: {
    paddingTop: 16,
    paddingBottom: 10,
  },
  followCard: {
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#fbf8f2',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  followIcon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: '#efe6d8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  followDate: {
    color: '#0c6740',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  followNotes: {
    marginTop: 4,
    color: '#19191f',
    fontSize: 13,
    lineHeight: 18,
  },
  nextActionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 8,
  },
  nextActionText: {
    flex: 1,
    minWidth: 0,
    color: '#717171',
    fontSize: 11,
    lineHeight: 15,
  },
  followDetailCard: {
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: 16,
  },
  detailRow: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#eee5d9',
    paddingVertical: 10,
  },
  detailLabel: {
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  detailValue: {
    marginTop: 3,
    color: '#19191f',
    fontSize: 13,
    lineHeight: 18,
  },
  detailScreen: {
    flex: 1,
  },
  leadDetailScroll: {
    flex: 1,
  },
  leadDetailContent: {
    paddingTop: 14,
    paddingBottom: 19,
  },
  profileCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    padding: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 84,
  },
  profileAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: {
    color: '#ffffff',
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
  },
  profileCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: 14,
  },
  profileName: {
    color: '#111111',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '700',
  },
  profileProperty: {
    marginTop: 2,
    color: '#b58526',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  statusBadgeStack: {
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 7,
  },
  stageBadge: {
    alignSelf: 'flex-start',
    minHeight: 24,
    borderRadius: 12,
    backgroundColor: '#f1eadf',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    marginTop: 7,
  },
  stageDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#3d5a40',
  },
  advisorStageBadge: {
    backgroundColor: '#fff9eb',
    borderWidth: 1,
    borderColor: '#e8c986',
  },
  advisorStageDot: {
    backgroundColor: '#c78d1c',
  },
  advisorStageText: {
    color: '#8a5d13',
  },
  stageText: {
    color: '#3d5a40',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  sourceRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
    marginLeft: 86,
  },
  infoPill: {
    maxWidth: 120,
    minHeight: 22,
    borderRadius: 11,
    backgroundColor: '#f8f2ee',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  infoPillText: {
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  infoGrid: {
    borderTopWidth: 0.5,
    borderTopColor: '#ded5c8',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
  },
  detailMetric: {
    width: '50%',
    minHeight: 34,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ded5c8',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  detailMetricWide: {
    width: '100%',
    borderBottomWidth: 0,
  },
  detailMetricText: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
  },
  detailSection: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    padding: 10,
    marginTop: 12,
  },
  detailSectionTitle: {
    color: '#19191f',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
    marginBottom: 8,
  },
  nextActionCard: {
    minHeight: 62,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d0dca8',
    backgroundColor: '#fbfcf5',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  nextActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextActionCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: 11,
  },
  nextActionTitle: {
    color: '#19191f',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '700',
  },
  nextActionMeta: {
    color: '#c78d1c',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  nextActionAdvisor: {
    color: '#717171',
    fontSize: 10,
    lineHeight: 13,
  },
  nextActionForm: {
    gap: 8,
    marginTop: 10,
  },
  nextActionInput: {
    minHeight: 39,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    color: '#19191f',
    fontSize: 13,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  nextActionDatePicker: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    padding: 8,
    gap: 8,
  },
  nextActionDateValue: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  nextActionDateText: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '600',
  },
  nextActionDateActions: {
    flexDirection: 'row',
    gap: 8,
  },
  nextActionDateButton: {
    flex: 1,
    minHeight: 32,
    borderRadius: 16,
    backgroundColor: '#eff6f1',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  nextActionDateButtonText: {
    color: '#0c6740',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
  },
  nextActionSaveButton: {
    minHeight: 39,
    borderRadius: 20,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  nextActionSaveButtonDisabled: {
    backgroundColor: '#9a9084',
  },
  nextActionSaveButtonText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
  },  
  quickActionsGrid: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  quickActionButton: {
    flex: 1,
    minWidth: 0,
    height: 62,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 4,
  },
  quickActionText: {
    color: '#19191f',
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  customStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 8,
  },
  customStatusSubtitle: {
    flexShrink: 1,
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  statusChipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  customStatusChip: {
    maxWidth: '100%',
    minHeight: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  customStatusChipActive: {
    borderColor: '#064b38',
    backgroundColor: '#064b38',
  },
  customStatusChipText: {
    color: '#19191f',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  customStatusChipTextActive: {
    color: '#ffffff',
  },
  customStatusEmpty: {
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  customStatusForm: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
  },
  customStatusInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    color: '#19191f',
    fontSize: 13,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  customStatusButton: {
    minWidth: 82,
    minHeight: 38,
    borderRadius: 19,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  customStatusButtonDisabled: {
    backgroundColor: '#9a9084',
  },
  customStatusButtonText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '800',
  },
  customStatusError: {
    marginTop: 7,
    color: '#a13b2f',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
  },  
  aiSection: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    padding: 10,
    marginTop: 12,
  },
  aiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  aiTitle: {
    color: '#19191f',
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '600',
  },
  aiSuggestionBox: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    overflow: 'hidden',
  },
  aiSuggestionRow: {
    minHeight: 58,
    borderBottomWidth: 0.5,
    borderBottomColor: '#ded5c8',
    backgroundColor: '#fffcfc',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  aiSuggestionIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#f1eadf',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiSuggestionCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  aiSuggestionTitle: {
    color: '#19191f',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  aiSuggestionBody: {
    marginTop: 2,
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
  },
  aiNote: {
    minHeight: 46,
    borderRadius: 11,
    backgroundColor: '#fff5e7',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginTop: 10,
  },
  aiNoteText: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  historySection: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    padding: 10,
    marginTop: 12,
  },
  timelineList: {
    gap: 0,
  },
  timelineRow: {
    flexDirection: 'row',
    minHeight: 46,
  },
  timelineRail: {
    width: 26,
    alignItems: 'center',
  },
  timelineDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineLine: {
    flex: 1,
    width: 1,
    backgroundColor: '#b8c2b2',
  },
  timelineCopy: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 8,
    paddingBottom: 12,
  },
  timelineTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timelineDate: {
    color: '#19191f',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  timelineType: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  timelineTime: {
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
  },
  timelineNotes: {
    marginTop: 3,
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
  },
  detailBottomActions: {
    flexDirection: 'row',
    gap: 6,
  },
  detailBottomDock: {
    borderTopWidth: 1,
    borderTopColor: '#ded5c8',
    backgroundColor: '#8b7446',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 10,
    marginHorizontal: -18,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 6,
  },
  secondaryDetailButton: {
    flex: 1.12,
    minWidth: 0,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  secondaryDetailButtonText: {
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
  },
  aiDetailButton: {
    flex: 0.7,
    minWidth: 0,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#d8b57d',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 8,
  },
  aiDetailButtonText: {
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
  },
  primaryDetailButton: {
    flex: 1.22,
    minWidth: 0,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  primaryDetailButtonText: {
    color: '#ffffff',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
  },
  historyScreen: {
    flex: 1,
  },
  historyHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  historyHeaderTitle: {
    color: '#3D5A40',
    fontSize: 22,
    lineHeight: 27,
    fontWeight: '700',
  },
  historyHeaderSubtitle: {
    marginTop: 3,
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  historyLeadCard: {
    minHeight: 104,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#fbf8f2',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginTop: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    elevation: 2,
  },
  historyLeadAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyLeadAvatarText: {
    color: '#ffffff',
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '700',
  },
  historyLeadCopy: {
    flex: 1,
    minWidth: 0,
    marginLeft: 12,
  },
  historyLeadName: {
    color: '#19191f',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  historyLeadId: {
    marginTop: 3,
    color: '#8d8783',
    fontSize: 11,
    lineHeight: 15,
  },
  historyLeadMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 9,
  },
  historyMetaPill: {
    maxWidth: '100%',
    minHeight: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#d0dca8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 9,
  },
  historyMetaPillText: {
    color: '#19191f',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
  },
  historyFilterScroll: {
    flexGrow: 0,
    marginTop: 14,
    marginHorizontal: -18,
  },
  historyFilterContent: {
    paddingHorizontal: 18,
    gap: 7,
  },
  historyFilterChip: {
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#fffcfc',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 13,
  },
  historyFilterChipActive: {
    backgroundColor: '#064b38',
    borderColor: '#064b38',
  },
  historyFilterText: {
    color: '#19191f',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
  },
  historyFilterTextActive: {
    color: '#ffffff',
  },
  fullHistoryContent: {
    paddingTop: 14,
    paddingBottom: 112,
  },
  historyEmptyCard: {
    minHeight: 286,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 28,
  },
  historyEmptyIcon: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: '#edf1e0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  historyEmptyTitle: {
    color: '#19191f',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
    textAlign: 'center',
  },
  historyEmptyText: {
    marginTop: 7,
    color: '#717171',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  fullHistoryRow: {
    flexDirection: 'row',
    minHeight: 100,
  },
  fullHistoryRail: {
    width: 54,
    alignItems: 'center',
  },
  fullHistorySmallDot: {
    position: 'absolute',
    left: 1,
    top: 17,
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#064b38',
    backgroundColor: '#ffffff',
    zIndex: 2,
  },
  fullHistoryIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    zIndex: 2,
  },
  fullHistoryLine: {
    position: 'absolute',
    top: 0,
    bottom: -8,
    left: 4,
    width: 1,
    backgroundColor: '#b8c2b2',
  },
  fullHistoryCard: {
    flex: 1,
    minWidth: 0,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    padding: 10,
    marginBottom: 8,
  },
  fullHistoryMetaRow: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  fullHistoryTimeGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  fullHistoryDate: {
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '600',
  },
  fullHistoryTime: {
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '500',
  },
  fullHistoryTag: {
    minHeight: 22,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#cbd8c3',
    backgroundColor: '#f5fbef',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  fullHistoryTagWarm: {
    borderColor: '#e8c986',
    backgroundColor: '#fff9eb',
  },
  fullHistoryTagText: {
    color: '#0c6740',
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  fullHistoryTagWarmText: {
    color: '#c78d1c',
  },
  fullHistoryBodyBox: {
    minHeight: 46,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#cfcfcf',
    backgroundColor: '#fbfbfb',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 6,
  },
  fullHistoryBodyText: {
    color: '#19191f',
    fontSize: 12,
    lineHeight: 16,
  },
  attachmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
  },
  attachmentText: {
    flex: 1,
    minWidth: 0,
    color: '#8d8783',
    fontSize: 11,
    lineHeight: 14,
  },
  historyActionDock: {
    position: 'absolute',
    left: -8,
    right: -8,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: '#d8d1c8',
    backgroundColor: '#fffcfc',
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 8,
  },
  historyV2ActionDock: {
    position: 'absolute',
    left: -18,
    right: -18,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: '#ded5c8',
    backgroundColor: '#fbf8f2',
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 6,
  },
  historyQuickActions: {
    flexDirection: 'row',
    gap: 5,
  },
  historyActionButton: {
    flex: 1,
    minWidth: 0,
    height: 34,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#d8d1c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 5,
  },
  historyActionButtonPrimary: {
    backgroundColor: '#064b38',
    borderColor: '#064b38',
  },
  historyActionText: {
    color: '#19191f',
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '700',
  },
  historyActionTextPrimary: {
    color: '#ffffff',
  },
  addActivityButton: {
    height: 36,
    borderRadius: 10,
    backgroundColor: '#064b38',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  addActivityText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
})
