import { StyleSheet } from 'react-native'

import { borderRadius, clientThemes, spacing, typography } from '@/lib/theme'

export const investorColors = clientThemes.investor

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: investorColors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: investorColors.border,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.full,
    backgroundColor: investorColors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: typography.h3.fontSize,
    fontWeight: '700',
    color: investorColors.text,
  },
  headerPlaceholder: {
    width: 40,
  },
  progressContainer: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  progressBar: {
    height: 4,
    backgroundColor: investorColors.border,
    borderRadius: borderRadius.full,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: investorColors.accent,
    borderRadius: borderRadius.full,
  },
  progressText: {
    fontSize: typography.caption.fontSize,
    color: investorColors.textMuted,
    textAlign: 'center',
    marginTop: spacing.sm,
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    flex: 1,
  },
  scrollContainer: {
    padding: spacing.md,
  },
  stepContent: {
    gap: spacing.lg,
  },
  stepTitle: {
    fontSize: typography.h3.fontSize,
    fontWeight: '700',
    color: investorColors.text,
  },
  stepSubtitle: {
    fontSize: typography.body.fontSize,
    color: investorColors.textSecondary,
    marginTop: -spacing.sm,
  },
  optionsGrid: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  optionCard: {
    flex: 1,
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: investorColors.border,
  },
  optionCardSelected: {
    borderColor: investorColors.accent,
    backgroundColor: investorColors.accent + '15',
  },
  optionLabel: {
    fontSize: typography.bodySmall.fontSize,
    color: investorColors.textSecondary,
    marginTop: spacing.sm,
    fontWeight: '500',
  },
  optionLabelSelected: {
    color: investorColors.text,
  },
  listingOptions: {
    gap: spacing.md,
  },
  listingOption: {
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    borderWidth: 2,
    borderColor: investorColors.border,
    position: 'relative',
  },
  listingOptionSelected: {
    borderColor: investorColors.accent,
    backgroundColor: investorColors.accent + '15',
  },
  checkIcon: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    width: 24,
    height: 24,
    borderRadius: borderRadius.full,
    backgroundColor: investorColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  listingOptionTitle: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: investorColors.text,
  },
  listingOptionTitleSelected: {
    color: investorColors.accent,
  },
  listingOptionDesc: {
    fontSize: typography.bodySmall.fontSize,
    color: investorColors.textSecondary,
    marginTop: spacing.xs,
  },
  externalAgencyContainer: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: investorColors.border,
  },
  formGroup: {
    gap: spacing.xs,
  },
  formRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  inputLabel: {
    fontSize: typography.bodySmall.fontSize,
    fontWeight: '500',
    color: investorColors.text,
  },
  inputHint: {
    fontSize: typography.caption.fontSize,
    color: investorColors.textMuted,
    marginBottom: spacing.xs,
  },
  input: {
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    fontSize: typography.body.fontSize,
    color: investorColors.text,
    borderWidth: 1,
    borderColor: investorColors.border,
  },
  inputWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.lg,
    paddingHorizontal: spacing.md,
    borderWidth: 1,
    borderColor: investorColors.border,
  },
  inputInner: {
    flex: 1,
    padding: spacing.md,
    fontSize: typography.body.fontSize,
    color: investorColors.text,
  },
  inputSuffix: {
    fontSize: typography.bodySmall.fontSize,
    color: investorColors.textMuted,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  amenityCard: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: investorColors.border,
    position: 'relative',
  },
  amenityCardSelected: {
    borderColor: investorColors.accent,
    backgroundColor: investorColors.accent + '15',
  },
  amenityLabel: {
    flex: 1,
    fontSize: typography.bodySmall.fontSize,
    color: investorColors.textSecondary,
  },
  amenityLabelSelected: {
    color: investorColors.text,
  },
  amenityCheck: {
    position: 'absolute',
    top: spacing.xs,
    right: spacing.xs,
    width: 18,
    height: 18,
    borderRadius: borderRadius.full,
    backgroundColor: investorColors.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  amenitiesHint: {
    fontSize: typography.caption.fontSize,
    color: investorColors.textMuted,
    textAlign: 'center',
  },
  photoButton: {
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: investorColors.accent,
    borderStyle: 'dashed',
    gap: spacing.sm,
  },
  photoButtonText: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: investorColors.accent,
  },
  photoButtonSubtext: {
    fontSize: typography.caption.fontSize,
    color: investorColors.textMuted,
  },
  photosGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  photoPreview: {
    width: 80,
    height: 80,
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: investorColors.border,
  },
  photoPreviewText: {
    fontSize: typography.caption.fontSize,
    color: investorColors.textMuted,
    marginTop: spacing.xs,
  },
  infoBox: {
    flexDirection: 'row',
    backgroundColor: investorColors.accent + '15',
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    gap: spacing.md,
    alignItems: 'flex-start',
  },
  infoBoxText: {
    flex: 1,
    fontSize: typography.bodySmall.fontSize,
    color: investorColors.textSecondary,
    lineHeight: 20,
  },
  finalStepContainer: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
  },
  finalIconContainer: {
    width: 80,
    height: 80,
    borderRadius: borderRadius.full,
    backgroundColor: investorColors.accent + '20',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  finalTitle: {
    fontSize: typography.h2.fontSize,
    fontWeight: '700',
    color: investorColors.text,
    marginBottom: spacing.xs,
  },
  finalSubtitle: {
    fontSize: typography.body.fontSize,
    color: investorColors.textSecondary,
    textAlign: 'center',
    marginBottom: spacing.xl,
  },
  finalInfoCard: {
    width: '100%',
    backgroundColor: investorColors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: investorColors.border,
  },
  finalInfoRow: {
    flexDirection: 'row',
    gap: spacing.md,
    alignItems: 'flex-start',
  },
  finalInfoContent: {
    flex: 1,
  },
  finalInfoTitle: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: investorColors.text,
  },
  finalInfoDesc: {
    fontSize: typography.bodySmall.fontSize,
    color: investorColors.textSecondary,
    marginTop: spacing.xs,
    lineHeight: 20,
  },
  finalDivider: {
    height: 1,
    backgroundColor: investorColors.border,
    marginVertical: spacing.md,
  },
  finalHint: {
    fontSize: typography.caption.fontSize,
    color: investorColors.textMuted,
    textAlign: 'center',
    marginTop: spacing.lg,
    paddingHorizontal: spacing.md,
  },
  warningBox: {
    width: '100%',
    marginTop: spacing.lg,
    backgroundColor: investorColors.accent + '15',
    borderColor: investorColors.accent,
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    gap: spacing.xs,
  },
  warningTitle: {
    color: investorColors.text,
    fontSize: typography.bodySmall.fontSize,
    fontWeight: '700',
  },
  warningText: {
    color: investorColors.textSecondary,
    fontSize: typography.caption.fontSize,
    lineHeight: 18,
  },
  footer: {
    padding: spacing.md,
    borderTopWidth: 1,
    borderTopColor: investorColors.border,
  },
  continueButton: {
    backgroundColor: investorColors.accent,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    alignItems: 'center',
  },
  continueButtonDisabled: {
    backgroundColor: investorColors.border,
  },
  continueButtonText: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: investorColors.primary,
  },
})
