import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  content: {
    paddingHorizontal: 10,
    paddingTop: 12,
    paddingBottom: 90,
  },
  topChrome: {
    height: 26,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    width: 44,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  datePill: {
    height: 20,
    borderRadius: 5,
    paddingHorizontal: 8,
    backgroundColor: '#cbb375',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  dateText: {
    fontSize: 11,
    color: '#19191f',
  },
  logoutButton: {
    height: 26,
    borderRadius: 5,
    backgroundColor: '#3d5a40',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 9,
    marginRight: 4,
  },
  logoutButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '600',
  },
  brand: {
    marginTop: 4,
    textAlign: 'center',
    color: '#3d5a40',
    fontSize: 36,
    lineHeight: 38,
    fontWeight: '300',
  },
  brandSmall: {
    textAlign: 'center',
    color: '#a46b40',
    fontSize: 12,
    letterSpacing: 0,
  },
  propertiesListButton: {
    marginTop: 12,
    alignSelf: 'center',
    minWidth: 228,
    height: 36,
    borderRadius: 7,
    backgroundColor: '#f1ebda',
    borderWidth: 1,
    borderColor: '#d6c7a3',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 12,
  },
  propertiesListButtonText: {
    color: '#3d5a40',
    fontSize: 13,
    fontWeight: '700',
  },
  headerBlock: {
    marginTop: 18,
    minHeight: 86,
  },
  overline: {
    color: '#3d5a40',
    fontSize: 19,
    marginBottom: 12,
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingRight: 42,
  },
  profileCopy: {
    flex: 1,
    minWidth: 0,
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 28,
    backgroundColor: '#cbb375',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#19191f',
  },
  greeting: {
    color: '#232323',
    fontSize: 25,
    lineHeight: 29,
  },
  helper: {
    color: '#8d8d8d',
    fontSize: 12,
    lineHeight: 15,
  },
  headerBell: {
    position: 'absolute',
    right: 20,
    bottom: 28,
  },
  heroCards: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 12,
    paddingHorizontal: 4,
  },
  propertiesCard: {
    width: 128,
    height: 104,
    borderRadius: 6,
    backgroundColor: '#3d5a40',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricOverline: {
    color: '#ffffff',
    fontSize: 10,
    lineHeight: 17,
  },
  propertiesValue: {
    color: '#cbb375',
    fontSize: 50,
    lineHeight: 59,
  },
  monthCard: {
    flex: 1,
    height: 104,
    borderRadius: 6,
    backgroundColor: '#f8f2ee',
    paddingHorizontal: 10,
    paddingTop: 9,
  },
  monthLabel: {
    color: '#c59b55',
    fontSize: 10,
    textAlign: 'center',
  },
  moneyRow: {
    paddingLeft: 8,
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  moneyValue: {
    color: '#2d3134',
    fontSize: 50,
    lineHeight: 45,
  },
  currency: {
    color: '#2d3134',
    fontSize: 13,
    marginLeft: 5,
    marginBottom: 10,
  },
  commission: {
    color: '#8a8a8a',
    fontSize: 10,
    marginTop: 9,
    paddingLeft: 75
  },
  sectionHeader: {
    marginTop: 18,
    marginHorizontal: 14,
    marginBottom: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sectionHeaderCompact: {
    marginTop: 0,
    marginHorizontal: 0,
  },
  sectionTitle: {
    flex: 1,
    color: '#0c6740',
    fontSize: 17,
  },
  sectionAction: {
    color: '#0c6740',
    fontSize: 12,
    flexShrink: 0,
  },
  horizontalStrip: {
    paddingHorizontal: 0,
    gap: 9,
  },
  priorityCard: {
    width: 100,
    height: 100,
    borderRadius: 16,
    backgroundColor: '#3d5a40',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    paddingBottom: 12,
  },
  priorityValue: {
    color: '#cbb375',
    fontSize: 40,
    lineHeight: 43,
  },
  priorityLabel: {
    color: '#ffffff',
    fontSize: 11,
    lineHeight: 10,
    textAlign: 'center',
  },
  advisorCard: {
    width: 125,
    height: 120,
    borderRadius: 20,
    backgroundColor: '#f8f2ee',
    padding: 8,
  },
  smallAvatar: {
    position: 'absolute',
    left: 8,
    top: 8,
    width: 35,
    height: 35,
    borderRadius: 20,
  },
  advisorName: {
    marginTop: 2,
    marginLeft: 40,
    color: '#232323',
    fontSize: 11,
    lineHeight: 13,
    minHeight: 26,
  },
  advisorMeta: {
    marginTop: 5,
    textAlign: 'center',
    color: '#3d5a40',
    fontSize: 10,
  },
  rentGoal: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  rentCurrent: {
    color: '#232323',
    fontSize: 26,
    lineHeight: 30,
  },
  rentTarget: {
    color: '#232323',
    fontSize: 18,
    lineHeight: 24,
  },
  statusPill: {
    alignSelf: 'center',
    minWidth: 70,
    height: 20,
    borderRadius: 4,
    backgroundColor: '#3d5a40',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingBottom: 2
  },
  statusText: {
    color: '#ffffff',
    fontSize: 10,
  },
  panel: {
    marginTop: 13,
    borderRadius: 8,
    backgroundColor: '#fffcfc',
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 7,
    elevation: 4,
  },
  panelSubtitle: {
    color: '#7e8b86',
    fontSize: 13,
    marginBottom: 10,
  },
  refreshCalendarButton: {
    alignSelf: 'flex-start',
    minHeight: 30,
    borderRadius: 6,
    backgroundColor: '#f1ebda',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  refreshCalendarButtonText: {
    color: '#3d5a40',
    fontSize: 11,
    fontWeight: '700',
  },
  appointmentsScroll: {
    maxHeight: 216,
  },
  appointments: {
    gap: 4,
  },
  emptyAppointments: {
    minHeight: 82,
    borderRadius: 6,
    backgroundColor: '#f8f2ee',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    gap: 7,
  },
  emptyAppointmentsText: {
    color: '#3d5a40',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
  },
  appointmentCard: {
    minHeight: 64,
    borderRadius: 6,
    backgroundColor: '#3d5a40',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 11,
    paddingRight: 8,
  },
  appointmentCopy: {
    flex: 1,
  },
  appointmentTitle: {
    color: '#cbb375',
    fontSize: 12,
    lineHeight: 14,
  },
  appointmentText: {
    color: '#ffffff',
    fontSize: 10,
    marginTop: 2,
  },
  appointmentDivider: {
    width: 1,
    height: 47,
    backgroundColor: '#d6c7a3',
    marginHorizontal: 10,
  },
  appointmentDate: {
    width: 93,
  },
  dateLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  appointmentDay: {
    color: '#ffffff',
    fontSize: 10,
  },
  appointmentTime: {
    color: '#cbb375',
    fontSize: 10,
    marginLeft: 19,
  },
  confirmPill: {
    marginTop: 2,
    marginLeft: 1,
    width: 76,
    height: 13,
    borderRadius: 3,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmText: {
    color: '#3d5a40',
    fontSize: 8,
  },
  deleteAppointmentButton: {
    width: 28,
    height: 28,
    borderRadius: 5,
    backgroundColor: '#8f2d2d',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  googleCalendarButton: {
    marginTop: 8,
    alignSelf: 'center',
    minWidth: 208,
    height: 34,
    borderRadius: 7,
    backgroundColor: '#0c6740',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 12,
  },
  googleCalendarButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  disconnectGoogleButton: {
    marginTop: 8,
    alignSelf: 'center',
    minWidth: 208,
    height: 34,
    borderRadius: 7,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#3d5a40',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 12,
  },
  disconnectGoogleButtonText: {
    color: '#3d5a40',
    fontSize: 13,
    fontWeight: '600',
  },
  googleCalendarSettings: {
    marginTop: 10,
    borderRadius: 7,
    backgroundColor: '#f8f2ee',
    padding: 10,
  },
  calendarSettingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 8,
  },
  calendarSettingsTitle: {
    flex: 1,
    color: '#3d5a40',
    fontSize: 13,
    fontWeight: '700',
  },
  calendarSmallButton: {
    minWidth: 78,
    height: 25,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  calendarSmallButtonText: {
    color: '#0c6740',
    fontSize: 10,
    fontWeight: '600',
  },
  calendarSettingsEmpty: {
    color: '#737373',
    fontSize: 11,
    lineHeight: 15,
    textAlign: 'center',
    paddingVertical: 10,
  },
  calendarList: {
    gap: 6,
  },
  calendarOptionRow: {
    minHeight: 42,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  calendarToggle: {
    width: 42,
    height: 24,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarToggleActive: {
    backgroundColor: '#3d5a40',
    borderColor: '#3d5a40',
  },
  calendarToggleText: {
    color: '#737373',
    fontSize: 9,
    fontWeight: '700',
  },
  calendarToggleTextActive: {
    color: '#ffffff',
  },
  calendarOptionCopy: {
    flex: 1,
    minWidth: 0,
  },
  calendarOptionTitle: {
    color: '#232323',
    fontSize: 11,
    fontWeight: '600',
  },
  calendarOptionMeta: {
    color: '#7e8b86',
    fontSize: 9,
    marginTop: 2,
  },
  calendarPrimaryButton: {
    minWidth: 52,
    height: 24,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#cbb375',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
  },
  calendarPrimaryButtonActive: {
    backgroundColor: '#cbb375',
  },
  calendarPrimaryButtonText: {
    color: '#3d5a40',
    fontSize: 9,
    fontWeight: '700',
  },
  calendarPrimaryButtonTextActive: {
    color: '#19191f',
  },
  calendarActionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 9,
  },
  calendarActionButton: {
    flex: 1,
    minHeight: 31,
    borderRadius: 6,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  calendarActionButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  calendarTestPanel: {
    marginTop: 10,
    borderRadius: 7,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e3ddd5',
    padding: 10,
  },
  calendarTestTitle: {
    color: '#3d5a40',
    fontSize: 13,
    fontWeight: '700',
  },
  calendarTestMeta: {
    color: '#7e8b86',
    fontSize: 10,
    marginTop: 3,
    marginBottom: 8,
  },
  calendarTestLabel: {
    color: '#3d5a40',
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 5,
  },
  calendarDestinationList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  calendarDestinationChip: {
    maxWidth: '48%',
    minHeight: 26,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    backgroundColor: '#fffcfc',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  calendarDestinationChipActive: {
    backgroundColor: '#3d5a40',
    borderColor: '#3d5a40',
  },
  calendarDestinationChipText: {
    color: '#3d5a40',
    fontSize: 9,
    fontWeight: '700',
  },
  calendarDestinationChipTextActive: {
    color: '#ffffff',
  },
  calendarTestActions: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
  },
  calendarTestButton: {
    flex: 1,
    height: 28,
    borderRadius: 5,
    backgroundColor: '#f1ebda',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarTestButtonText: {
    color: '#3d5a40',
    fontSize: 10,
    fontWeight: '700',
  },
  calendarTestInput: {
    minHeight: 34,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    color: '#232323',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 6,
    marginBottom: 6,
    backgroundColor: '#fffcfc',
  },
  calendarPicker: {
    marginBottom: 6,
  },
  calendarPickerValue: {
    minHeight: 34,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    color: '#232323',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 8,
    backgroundColor: '#fffcfc',
  },
  calendarPickerActions: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
  },
  calendarPickerButton: {
    flex: 1,
    height: 28,
    borderRadius: 5,
    backgroundColor: '#f1ebda',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarPickerButtonText: {
    color: '#3d5a40',
    fontSize: 10,
    fontWeight: '700',
  },
  calendarTestCreateButton: {
    minHeight: 32,
    borderRadius: 6,
    backgroundColor: '#3d5a40',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    marginTop: 2,
  },
  calendarTestCreateButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
  },
  centerButton: {
    marginTop: 8,
    alignSelf: 'center',
    width: 158,
    height: 33,
    borderRadius: 6,
    backgroundColor: '#cbb375',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  centerButtonText: {
    color: '#3d5a40',
    fontSize: 14,
  },
  followGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
    marginBottom: 9,
  },
  statTile: {
    flex: 1,
    height: 120,
    width: 120,
    borderRadius: 6,
    backgroundColor: '#f1ebda',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statValue: {
    color: '#3d5a40',
    fontSize: 28,
    lineHeight: 35,
  },
  statLabel: {
    color: '#737373',
    fontSize: 11,
    textAlign: 'center',
  },
  subSectionTitle: {
    color: '#0c6740',
    fontSize: 13,
    marginBottom: 8,
  },
  funnelRow: {
    height: 64,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    marginBottom: 9,
  },
  funnelItem: {
    width: 68,
    alignItems: 'center',
    justifyContent: 'center',
  },
  funnelValue: {
    color: '#3d5a40',
    fontSize: 27,
  },
  funnelLabel: {
    color: '#737373',
    fontSize: 10,
    textAlign: 'center',
  },
  alertRow: {
    height: 36,
    borderRadius: 6,
    backgroundColor: '#ffe8e4',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    marginBottom: 7,
    gap: 10,
  },
  alertText: {
    flex: 1,
    color: '#3d3d3d',
    fontSize: 12,
  },
  focusBox: {
    borderRadius: 6,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingTop: 7,
    paddingBottom: 6,
    marginTop: 2,
  },
  focusRow: {
    height: 37,
    flexDirection: 'row',
    alignItems: 'center',
  },
  focusDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#dedede',
  },
  focusName: {
    flex: 1,
    color: '#0c6740',
    fontSize: 12,
  },
  focusMetric: {
    width: 92,
    color: '#0c6740',
    fontSize: 12,
    marginLeft: 4,
  },
  alertDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#ff8d8d',
    marginRight: 8,
  },
  focusLate: {
    width: 70,
    color: '#0c6740',
    fontSize: 12,
  },
  detailButtons: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 29,
  },
  miniButton: {
    width: 158,
    height: 33,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#e3ddd5',
  },
  miniButtonText: {
    color: '#0c6740',
    fontSize: 12,
  },
  miniButtonPrimary: {
    backgroundColor: '#0c6740',
    borderColor: '#0c6740',
  },
  miniButtonTextPrimary: {
    color: '#ffffff',
  },
  campaignList: {
    gap: 7,
  },
  campaignRow: {
    height: 58,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  propertyThumb: {
    width: 70,
    height: 45,
    borderRadius: 5,
    backgroundColor: '#e7d6c2',
  },
  campaignCopy: {
    flex: 1,
    marginLeft: 8,
  },
  campaignTitle: {
    color: '#232323',
    fontSize: 11,
  },
  campaignDate: {
    color: '#747474',
    fontSize: 8,
    marginTop: 3,
  },
  campaignStatus: {
    alignSelf: 'flex-start',
    borderRadius: 4,
    paddingHorizontal: 6,
    height: 15,
    justifyContent: 'center',
    marginTop: 5,
  },
  campaignStatusText: {
    color: '#ffffff',
    fontSize: 9,
  },
  budgetBox: {
    width: 86,
  },
  budgetLabel: {
    color: '#3d5a40',
    fontSize: 8,
  },
  budgetValue: {
    color: '#0c6740',
    fontSize: 13,
    textAlign: 'right',
    paddingRight: 6,
  },
})
