import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollContent: {
    alignItems: 'center',
    paddingBottom: 90,
  },
  canvas: {
    minHeight: 956,
    backgroundColor: '#ffffff',
  },
  headerCanvas: {
    height: 205,
  },
  backButton: {
    position: 'absolute',
    left: 16,
    top: 34,
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    position: 'absolute',
    left: 63,
    top: 32,
    color: '#3D5A40',
    fontSize: 23,
    lineHeight: 25,
    fontWeight: '500',
  },
  subtitle: {
    position: 'absolute',
    left: 63,
    top: 57,
    color: '#afafaf',
    fontSize: 16,
  },
  exportPanel: {
    position: 'absolute',
    right: 14,
    bottom: 84,
    width: 120,
    height: 152,
    borderRadius: 13,
    backgroundColor: 'rgba(254,254,254,0.86)',
    borderWidth: 0.5,
    borderColor: '#969696',
    alignItems: 'center',
    paddingTop: 11,
    zIndex: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
  },
  exportButtonSecondary: {
    width: 102,
    height: 45,
    borderRadius: 9.5,
    backgroundColor: 'rgba(254,254,254,0.76)',
    borderWidth: 0.5,
    borderColor: '#969696',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exportButtonSecondaryText: {
    color: '#0c6740',
    fontSize: 13,
    lineHeight: 15,
    textAlign: 'center',
    fontWeight: '500',
  },
  exportButtonPrimary: {
    marginTop: 6,
    width: 102,
    height: 45,
    borderRadius: 9.5,
    backgroundColor: '#0c6740',
    borderWidth: 0.5,
    borderColor: 'rgba(0,0,0,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  exportButtonPrimaryText: {
    color: '#ffffff',
    fontSize: 13,
    lineHeight: 15,
    textAlign: 'center',
    fontWeight: '500',
  },
  exportHint: {
    marginTop: 8,
    color: '#929594',
    fontSize: 8,
    lineHeight: 10,
    textAlign: 'center',
  },
  mapFloatingButton: {
    position: 'absolute',
    alignSelf: 'center',
    bottom: 83,
    width: 103,
    height: 45,
    borderRadius: 40,
    backgroundColor: '#0c6740e1',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 23,
    paddingVertical: 10,
    zIndex: 25,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.14,
    shadowRadius: 5,
    elevation: 6,
  },
  mapFloatingButtonText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
  },
  controlsBlock: {
    position: 'absolute',
    left: 17,
    right: 17,
    top: 95,
    gap: 11,
  },
  searchRow: {
    width: '100%',
    height: 43,
    borderRadius: 9.5,
    borderColor: '#969696',
    borderWidth: 1,
    backgroundColor: '#FEFEFE',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 12,
    padding: 0,
  },
  controlsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  controlButton: {
    flex: 1,
    minWidth: 0,
    height: 36,
    borderRadius: 9.5,
    backgroundColor: '#FEFEFE',
    borderColor: '#969696',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  toggleText: {
    color: '#0c6740',
    fontSize: 12,
  },
  filterBadge: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadgeText: {
    color: '#ffffff',
    fontSize: 8,
    lineHeight: 10,
  },
  list: {
    gap: 8,
    alignItems: 'center',
  },
  propertyCard: {
    width: 405,
    height: 185,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    borderWidth: 0.5,
    borderColor: 'rgba(0,0,0,0.22)',
    flexDirection: 'row',
    padding: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  imageWrap: {
    width: 198,
    height: 177,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#ead4bc',
    borderWidth: 0.5,
    borderColor: 'rgba(0,0,0,0.22)',
  },
  propertyImage: {
    width: 198,
    height: 177,
  },
  imagePlaceholder: {
    flex: 1,
    backgroundColor: '#ead4bc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationPill: {
    position: 'absolute',
    left: 5,
    top: 7,
    height: 17,
    maxWidth: 84,
    borderRadius: 7,
    backgroundColor: '#f6efe3',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 5,
  },
  locationPillText: {
    flexShrink: 1,
    color: '#505050',
    fontSize: 8,
    fontWeight: '600',
  },
  availablePill: {
    position: 'absolute',
    right: 8,
    top: 7,
    width: 57,
    height: 17,
    borderRadius: 7,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
  },
  availablePillText: {
    color: '#ffffff',
    fontSize: 8,
    fontWeight: '600',
  },
  propertyInfo: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 12,
    paddingTop: 1,
    paddingRight: 4,
  },
  propertyTitle: {
    color: '#0c6740',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '500',
  },
  propertyCode: {
    marginTop: 2,
    color: '#929594',
    fontSize: 9,
    lineHeight: 12,
  },
  priceRow: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  price: {
    color: '#0c6740',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '400',
  },
  priceMeta: {
    color: '#c59b55',
    fontSize: 9.5,
    marginBottom: 1,
  },
  featuresRow: {
    height: 42,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#d8d0c5',
  },
  feature: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
  },
  featureValueRow: {
    height: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  featureValue: {
    flexShrink: 1,
    color: '#0c6740',
    fontSize: 9,
    fontWeight: '400',
  },
  featureLabel: {
    color: '#929594',
    fontSize: 7,
  },
  featureDivider: {
    width: 0.5,
    height: 19,
    backgroundColor: '#d8d0c5',
  },
  amenitiesRow: {
    height: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: '#d8d0c5',
  },
  amenity: {
    width: '24%',
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  amenityText: {
    color: '#929594',
    fontSize: 6.5,
    lineHeight: 8,
    textAlign: 'center',
  },
  detailTagsRow: {
    marginTop: 4,
    flexDirection: 'row',
    gap: 9,
  },
  detailTag: {
    flex: 1,
    minWidth: 0,
    height: 17,
    borderRadius: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingHorizontal: 5,
  },
  detailTagBlue: {
    backgroundColor: 'rgba(107,223,255,0.48)',
    borderWidth: 0.5,
    borderColor: '#6bdfff',
  },
  detailTagWarm: {
    backgroundColor: 'rgba(197,155,85,0.48)',
  },
  detailTagText: {
    flexShrink: 1,
    color: '#0c6740',
    fontSize: 7,
  },
  detailTagTextWarm: {
    color: '#bd7600',
  },
  cardFooter: {
    flex: 1,
    minHeight: 29,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingBottom: 1,
  },
  detailLink: {
    color: '#0c6740',
    fontSize: 11,
    fontWeight: '500',
  },
  favoriteButton: {
    width: 27,
    height: 27,
    borderRadius: 14,
    backgroundColor: '#f6efe3',
    alignItems: 'center',
    justifyContent: 'center',
  },
})
