import { Platform, StyleSheet } from 'react-native'

const serifFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'serif',
})

export const registerOwnerAccessStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fefbf6',
  },
  backButton: {
    position: 'absolute',
    left: 37,
    top: 21,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 70,
    paddingBottom: 40,
  },
  main: {
    width: '100%',
    maxWidth: 378,
    alignItems: 'center',
    gap: 36,
  },
  topSection: {
    width: '100%',
    alignItems: 'center',
    gap: 36,
  },
  logoWrap: {
    alignItems: 'center',
    marginBottom: -11,
  },
  progressRow: {
    width: 341,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  progressLabel: {
    color: '#e4ac73',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 17,
  },
  progressTrack: {
    flex: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#ddd5c6',
  },
  progressActive: {
    width: '25%',
    height: 2,
    borderRadius: 2,
    backgroundColor: '#c2824b',
  },
  header: {
    width: 341,
    alignItems: 'flex-start',
  },
  title: {
    width: '100%',
    color: '#155721',
    fontFamily: serifFont,
    fontSize: 40,
    fontWeight: '700',
    lineHeight: 50,
  },
  subtitle: {
    width: '100%',
    marginTop: 4,
    color: '#000000',
    fontSize: 13,
    lineHeight: 20,
    letterSpacing: 0.65,
    paddingRight: 24,
  },
  form: {
    width: '100%',
    gap: 16,
    paddingHorizontal: 10,
  },
  inputShell: {
    width: '100%',
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e5dfd2',
    borderRadius: 12,
    backgroundColor: '#fefdfb',
    paddingHorizontal: 16,
  },
  inputIcon: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  input: {
    flex: 1,
    height: 54,
    paddingVertical: 0,
    color: '#1e2d29',
    fontSize: 13,
    fontWeight: '600',
  },
  passwordInput: {
    paddingRight: 42,
  },
  passwordToggle: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  infoCard: {
    width: 358,
    minHeight: 70,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e3c47c',
    borderRadius: 14,
    backgroundColor: '#f8f0e5',
    paddingHorizontal: 22,
    gap: 34,
  },
  infoText: {
    flex: 1,
    color: '#1e2d29',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 19,
  },
  errorText: {
    width: 341,
    marginTop: -22,
    color: '#b42318',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  continueButton: {
    width: 304,
    height: 45,
    borderRadius: 12,
    backgroundColor: '#013f2f',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 25,
    position: 'relative',
  },
  continueButtonDisabled: {
    opacity: 0.62,
  },
  continueButtonText: {
    color: '#ffffff',
    fontSize: 15,
    lineHeight: 16,
    textAlign: 'center',
  },
  continueButtonIcon: {
    position: 'absolute',
    right: 24,
  },
})

