import type { User, Property, PropertyLead, Appointment, Notification, Commission, ActiveRental, Message, Conversation, PropertyEarnings, Campaign, SaleRentRegistration } from './types'

// Usuarios de ejemplo
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Carlos Rodriguez',
    email: 'carlos@email.com',
    phone: '+52 55 1234 5678',
    systemRole: 'CLIENT',
    investment: true,
    tenant: false,
    referralCode: 'CARLOS2024',
    createdAt: '2024-01-15',
  },
  {
    id: 'user-2',
    name: 'Maria Garcia',
    email: 'maria@email.com',
    phone: '+52 55 2345 6789',
    systemRole: 'CLIENT',
    investment: false,
    tenant: false,
    referralCode: 'MARIA2024',
    createdAt: '2024-02-20',
  },
  {
    id: 'user-3',
    name: 'Juan Martinez',
    email: 'juan@email.com',
    phone: '+52 55 3456 7890',
    systemRole: 'CLIENT',
    investment: false,
    tenant: true,
    referralCode: 'JUAN2024',
    createdAt: '2024-03-10',
  },
  {
    id: 'user-4',
    name: 'Ana Lopez',
    email: 'ana@iniciorealestate.com',
    phone: '+52 55 4567 8901',
    systemRole: 'AGENT',
    investment: false,
    tenant: false,
    createdAt: '2023-06-01',
  },
  {
    id: 'user-5',
    name: 'Roberto Sanchez',
    email: 'roberto@iniciorealestate.com',
    phone: '+52 55 5678 9012',
    systemRole: 'ADMIN',
    investment: false,
    tenant: false,
    createdAt: '2023-01-01',
  },
  {
    id: 'user-6',
    name: 'Daniela Morales',
    email: 'daniela@iniciorealestate.com',
    phone: '+52 55 6789 0123',
    systemRole: 'AGENT',
    investment: false,
    tenant: false,
    createdAt: '2023-08-12',
  },
]

// Propiedades de ejemplo
export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    title: 'Casa Moderna en Polanco',
    address: 'Av. Presidente Masaryk 123',
    city: 'Ciudad de Mexico',
    price: 8500000,
    currentValue: 9200000,
    type: 'house',
    status: 'owned',
    bedrooms: 4,
    bathrooms: 3,
    sqMeters: 350,
    size: 350,
    description: 'Hermosa casa moderna con acabados de lujo',
    amenities: ['Jardin', 'Alberca', 'Estacionamiento 3 autos', 'Cocina integral', 'Cuarto de servicio'],
    features: ['Jardin', 'Alberca', 'Estacionamiento 3 autos'],
    ownerId: 'user-1',
    agentId: 'user-4',
    purchasedWithUs: true,
    createdAt: '2024-01-20',
  },
  {
    id: 'prop-2',
    title: 'Departamento Vista al Mar',
    address: 'Blvd. Kukulcan Km 12',
    city: 'Cancun',
    price: 4200000,
    type: 'apartment',
    status: 'for_sale',
    bedrooms: 2,
    bathrooms: 2,
    sqMeters: 120,
    size: 120,
    description: 'Departamento con vista panoramica al mar',
    amenities: ['Vista al mar', 'Gimnasio', 'Seguridad 24/7'],
    features: ['Vista al mar', 'Gimnasio', 'Seguridad 24/7'],
    agentId: 'user-4',
    purchasedWithUs: false,
    createdAt: '2024-02-15',
  },
  {
    id: 'prop-3',
    title: 'Penthouse en Santa Fe',
    address: 'Av. Santa Fe 500',
    city: 'Ciudad de Mexico',
    price: 12000000,
    type: 'apartment',
    status: 'for_rent',
    bedrooms: 3,
    bathrooms: 3,
    sqMeters: 280,
    size: 280,
    monthlyRent: 85000,
    description: 'Penthouse de lujo con terraza privada',
    amenities: ['Terraza', 'Vista panoramica', 'Amenidades'],
    features: ['Terraza', 'Vista panoramica', 'Amenidades'],
    agentId: 'user-4',
    purchasedWithUs: false,
    createdAt: '2024-03-01',
  },
  {
    id: 'prop-4',
    title: 'Terreno en Tulum',
    address: 'Carretera Tulum-Boca Paila',
    city: 'Tulum',
    price: 2800000,
    type: 'land',
    status: 'available',
    sqMeters: 1500,
    size: 1500,
    description: 'Terreno ideal para desarrollo turistico',
    amenities: ['Cerca de la playa', 'Servicios disponibles'],
    features: ['Cerca de la playa', 'Servicios disponibles'],
    agentId: 'user-4',
    purchasedWithUs: false,
    createdAt: '2024-03-15',
  },
  {
    id: 'prop-5',
    title: 'Casa Colonial en Centro',
    address: 'Calle 60 x 47',
    city: 'Merida',
    price: 5500000,
    currentValue: 6200000,
    type: 'house',
    status: 'rented',
    bedrooms: 5,
    bathrooms: 4,
    sqMeters: 420,
    size: 420,
    monthlyRent: 45000,
    description: 'Casa colonial restaurada en el centro historico',
    amenities: ['Patio interior', 'Techos altos', 'Acabados originales', 'Cocina equipada', 'Bodega'],
    features: ['Patio interior', 'Techos altos', 'Acabados originales'],
    ownerId: 'user-1',
    agentId: 'user-4',
    purchasedWithUs: true,
    createdAt: '2024-01-10',
  },
  // Nuevas propiedades del inversionista (user-1)
  {
    id: 'prop-6',
    title: 'Departamento en Condesa',
    address: 'Av. Amsterdam 234',
    city: 'Ciudad de Mexico',
    price: 4800000,
    currentValue: 5100000,
    type: 'apartment',
    status: 'for_rent',
    bedrooms: 2,
    bathrooms: 2,
    sqMeters: 95,
    size: 95,
    monthlyRent: 28000,
    description: 'Departamento moderno en la mejor zona de la Condesa',
    amenities: ['Balcon', 'Gimnasio', 'Roof garden', 'Pet friendly', 'Estacionamiento'],
    features: ['Balcon', 'Gimnasio', 'Roof garden'],
    ownerId: 'user-1',
    agentId: 'user-4',
    purchasedWithUs: true,
    createdAt: '2023-08-15',
  },
  {
    id: 'prop-7',
    title: 'Casa en Coyoacan',
    address: 'Calle Francisco Sosa 156',
    city: 'Ciudad de Mexico',
    price: 7200000,
    currentValue: 7800000,
    type: 'house',
    status: 'for_sale',
    bedrooms: 4,
    bathrooms: 3,
    sqMeters: 280,
    size: 280,
    description: 'Hermosa casa con jardin en zona historica de Coyoacan',
    amenities: ['Jardin amplio', 'Estudio', 'Cuarto de servicio', 'Bodega', 'Chimenea'],
    features: ['Jardin amplio', 'Estudio', 'Cuarto de servicio'],
    ownerId: 'user-1',
    agentId: 'user-4',
    purchasedWithUs: false,
    createdAt: '2022-03-20',
  },
  {
    id: 'prop-8',
    title: 'Loft Industrial en Roma Norte',
    address: 'Calle Durango 89',
    city: 'Ciudad de Mexico',
    price: 3500000,
    currentValue: 3900000,
    type: 'apartment',
    status: 'rented',
    bedrooms: 1,
    bathrooms: 1,
    sqMeters: 75,
    size: 75,
    monthlyRent: 22000,
    description: 'Loft con diseno industrial, techos altos y acabados de lujo',
    amenities: ['Techos dobles', 'Cocina abierta', 'Terraza privada', 'Aire acondicionado'],
    features: ['Techos dobles', 'Cocina abierta', 'Terraza privada'],
    ownerId: 'user-1',
    agentId: 'user-4',
    purchasedWithUs: true,
    createdAt: '2023-11-05',
  },
  {
    id: 'prop-9',
    title: 'Penthouse en Interlomas',
    address: 'Av. Jesus del Monte 300',
    city: 'Huixquilucan',
    price: 15000000,
    currentValue: 16500000,
    type: 'apartment',
    status: 'for_sale',
    bedrooms: 4,
    bathrooms: 4,
    sqMeters: 320,
    size: 320,
    description: 'Penthouse de lujo con vista panoramica y terraza de 100m2',
    amenities: ['Terraza 100m2', 'Jacuzzi', 'Vista panoramica', 'Cine en casa', 'Cava de vinos', 'Elevador privado'],
    features: ['Terraza 100m2', 'Jacuzzi', 'Vista panoramica'],
    ownerId: 'user-1',
    agentId: 'user-4',
    purchasedWithUs: true,
    createdAt: '2024-02-01',
  },
  {
    id: 'prop-10',
    title: 'Casa de Playa en Puerto Escondido',
    address: 'Calle Zicatela 45',
    city: 'Puerto Escondido',
    price: 6800000,
    currentValue: 7500000,
    type: 'house',
    status: 'for_rent',
    bedrooms: 3,
    bathrooms: 2,
    sqMeters: 180,
    size: 180,
    monthlyRent: 55000,
    description: 'Casa frente al mar ideal para renta vacacional',
    amenities: ['Vista al mar', 'Alberca', 'Palapa', 'Hamacas', 'Parrilla', 'Estacionamiento'],
    features: ['Vista al mar', 'Alberca', 'Palapa'],
    ownerId: 'user-1',
    agentId: 'user-4',
    purchasedWithUs: false,
    createdAt: '2023-05-10',
  },
]

// Leads de ejemplo
export const mockLeads: PropertyLead[] = [
  {
    id: 'lead-1',
    propertyId: 'prop-2',
    agentId: 'user-4',
    name: 'Pedro Hernandez',
    phone: '+52 55 1111 2222',
    email: 'pedro@email.com',
    status: 'nuevo',
    source: 'Facebook',
    contactType: 'whatsapp',
    searchIntent: 'sale',
    notes: 'Pidio informacion general del departamento y rango de precio.',
    createdDate: '2024-05-01',
    firstContactDate: '2024-05-01',
    assignedAgentName: 'Ana Lopez',
    followUps: [
      {
        id: 'lead-1-fu-1',
        date: '2024-05-01',
        type: 'whatsapp',
        notes: 'Primer contacto por WhatsApp. Se compartio brochure y precio de salida.',
      },
      {
        id: 'lead-1-fu-2',
        date: '2024-05-03',
        type: 'call',
        notes: 'Llamada breve para resolver dudas sobre mantenimiento y amenidades.',
      },
    ],
  },
  {
    id: 'lead-2',
    propertyId: 'prop-3',
    agentId: 'user-4',
    name: 'Laura Diaz',
    phone: '+52 55 3333 4444',
    email: 'laura@email.com',
    status: 'contactado',
    source: 'Instagram',
    contactType: 'email',
    searchIntent: 'rent',
    notes: 'Mostro interes por renta a mediano plazo y pregunto por disponibilidad inmediata.',
    createdDate: '2024-04-28',
    firstContactDate: '2024-04-28',
    lastContactDate: '2024-05-02',
    assignedAgentName: 'Ana Lopez',
    followUps: [
      {
        id: 'lead-2-fu-1',
        date: '2024-04-29',
        type: 'email',
        notes: 'Se envio presentacion con fotos, ubicacion y condiciones de renta.',
      },
      {
        id: 'lead-2-fu-2',
        date: '2024-05-02',
        type: 'meeting',
        notes: 'Reunion virtual para revisar opciones de agenda y perfil del cliente.',
      },
    ],
  },
  {
    id: 'lead-3',
    propertyId: 'prop-2',
    agentId: 'user-4',
    name: 'Miguel Torres',
    phone: '+52 55 5555 6666',
    status: 'cita_agendada',
    source: 'Referido',
    contactType: 'call',
    searchIntent: 'sale',
    notes: 'Llego por recomendacion de un cliente anterior. Ya tiene visita programada.',
    createdDate: '2024-04-20',
    firstContactDate: '2024-04-20',
    lastContactDate: '2024-05-01',
    assignedAgentName: 'Ana Lopez',
    followUps: [
      {
        id: 'lead-3-fu-1',
        date: '2024-04-21',
        type: 'call',
        notes: 'Se validaron necesidades del cliente y preferencia de horario para visita.',
      },
      {
        id: 'lead-3-fu-2',
        date: '2024-05-01',
        type: 'visit',
        notes: 'Se confirmo visita presencial para conocer el inmueble y la zona.',
      },
    ],
  },
  {
    id: 'lead-4',
    propertyId: 'prop-4',
    agentId: 'user-4',
    name: 'Sofia Ruiz',
    phone: '+52 55 7777 8888',
    email: 'sofia@empresa.com',
    status: 'negociando',
    source: 'Sitio Web',
    contactType: 'meeting',
    searchIntent: 'sale',
    notes: 'Empresa interesada en compra, actualmente comparando opciones y condiciones.',
    createdDate: '2024-04-15',
    firstContactDate: '2024-04-15',
    lastContactDate: '2024-05-03',
    assignedAgentName: 'Ana Lopez',
    followUps: [
      {
        id: 'lead-4-fu-1',
        date: '2024-04-16',
        type: 'email',
        notes: 'Se envio informacion corporativa y expediente tecnico del terreno.',
      },
      {
        id: 'lead-4-fu-2',
        date: '2024-05-03',
        type: 'meeting',
        notes: 'Reunion con tomadores de decision para revisar esquema de negociacion.',
      },
    ],
  },
  {
    id: 'lead-5',
    propertyId: 'prop-3',
    agentId: 'user-6',
    assignedAgentName: 'Daniela Morales',
    name: 'Arturo Benitez',
    phone: '+52 55 9988 7766',
    email: 'arturo@email.com',
    status: 'visitado',
    source: 'Portal Inmuebles24',
    contactType: 'visit',
    searchIntent: 'rent',
    notes: 'Cliente corporativo buscando renta inmediata para ejecutivo extranjero.',
    createdDate: '2024-05-04',
    firstContactDate: '2024-05-04',
    lastContactDate: '2024-05-06',
    followUps: [
      {
        id: 'lead-5-fu-1',
        date: '2024-05-04',
        type: 'call',
        notes: 'Se compartio disponibilidad y requisitos de renta.',
      },
      {
        id: 'lead-5-fu-2',
        date: '2024-05-06',
        type: 'visit',
        notes: 'Visita presencial completada con decision pendiente del cliente.',
      },
    ],
  },
]

// Citas de ejemplo
export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    propertyId: 'prop-2',
    userId: 'user-2',
    agentId: 'user-4',
    date: '2024-05-10',
    time: '10:00',
    status: 'confirmed',
    createdAt: '2024-05-01',
  },
  {
    id: 'apt-2',
    propertyId: 'prop-3',
    userId: 'user-2',
    agentId: 'user-4',
    date: '2024-05-12',
    time: '15:00',
    status: 'pending',
    createdAt: '2024-05-02',
  },
]

// Notificaciones de ejemplo
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    title: 'Actualizacion de valor',
    message: 'Tu propiedad en Polanco ha incrementado su valor estimado',
    type: 'success',
    read: false,
    createdAt: '2024-05-05T10:00:00',
  },
  {
    id: 'notif-2',
    userId: 'user-4',
    title: 'Nuevo lead asignado',
    message: 'Se te ha asignado un nuevo lead para la propiedad en Cancun',
    type: 'info',
    read: false,
    createdAt: '2024-05-05T09:30:00',
  },
]

// Comisiones de ejemplo
export const mockCommissions: Commission[] = [
  {
    id: 'comm-1',
    agentId: 'user-4',
    propertyId: 'prop-5',
    transactionType: 'rent',
    amount: 4500,
    rate: 10,
    status: 'paid',
    createdDate: '2024-01-15',
    paidDate: '2024-02-01',
  },
  {
    id: 'comm-2',
    agentId: 'user-4',
    propertyId: 'prop-2',
    transactionType: 'sale',
    amount: 210000,
    rate: 5,
    status: 'pending',
    createdDate: '2024-05-01',
  },
  {
    id: 'comm-3',
    agentId: 'user-6',
    propertyId: 'prop-3',
    transactionType: 'rent',
    amount: 8500,
    rate: 10,
    status: 'approved',
    createdDate: '2024-05-03',
  },
  {
    id: 'comm-4',
    agentId: 'user-6',
    propertyId: 'prop-10',
    transactionType: 'rent',
    amount: 12000,
    rate: 12,
    status: 'paid',
    createdDate: '2024-04-10',
    paidDate: '2024-04-30',
  },
]

export const mockSaleRentRegistrations: SaleRentRegistration[] = [
  {
    id: 'reg-1',
    propertyId: 'prop-2',
    agentId: 'user-4',
    type: 'sale',
    transactionAmount: 4200000,
    originalPrice: 4200000,
    commissionRate: 5,
    commissionAmount: 210000,
    isExternalProperty: false,
    isSharedCommission: false,
    referralValid: false,
    clientName: 'Pedro Hernandez',
    clientPhone: '+52 55 1111 2222',
    clientEmail: 'pedro@email.com',
    documents: [],
    pendingDocuments: ['Contrato firmado', 'INE del cliente'],
    status: 'pending_review',
    createdDate: '2024-05-01',
    notes: 'Cliente ya envio carta intencion. Falta validacion documental.',
  },
  {
    id: 'reg-2',
    propertyId: 'prop-3',
    agentId: 'user-6',
    type: 'rent',
    transactionAmount: 85000,
    originalPrice: 85000,
    startDate: '2024-06-01',
    endDate: '2025-05-31',
    duration: 12,
    commissionRate: 10,
    commissionAmount: 8500,
    isExternalProperty: true,
    isSharedCommission: true,
    sharedAgentId: 'external-1',
    sharedAgentName: 'Patricia Vega',
    sharedCommissionRate: 5,
    agentCommission: 4250,
    sharedAgentCommission: 4250,
    referralValid: true,
    referralUserName: 'Luis Franco',
    referralAmount: 1500,
    clientName: 'Arturo Benitez',
    clientPhone: '+52 55 9988 7766',
    clientEmail: 'arturo@email.com',
    documents: [],
    pendingDocuments: ['Contrato de arrendamiento'],
    status: 'approved',
    createdDate: '2024-05-06',
    reviewedDate: '2024-05-08',
    reviewedBy: 'Roberto Sanchez',
    notes: 'Operacion aprobada. Programar carga de contrato final.',
  },
]

// Renta activa de ejemplo (para inquilinos)
export const mockActiveRental: ActiveRental = {
  id: 'rental-1',
  propertyId: 'prop-5',
  tenantId: 'user-3',
  landlordId: 'user-1',
  agentId: 'user-4',
  startDate: '2024-01-15',
  endDate: '2025-01-15',
  monthlyRent: 45000,
  paymentDay: 5,
  depositAmount: 90000,
  rules: [
    'No se permiten mascotas grandes',
    'Horario de silencio de 10pm a 8am',
    'No se permite subarrendar',
    'Mantenimiento de jardin incluido',
    'Maximo 4 ocupantes',
  ],
  utilities: {
    electricity: {
      provider: 'CFE',
      phone: '071',
      accountNumber: '123456789012',
    },
    water: {
      provider: 'SAPAS',
      phone: '+52 55 5555 1234',
      accountNumber: '987654321',
    },
    gas: {
      provider: 'Gas Natural',
      phone: '+52 55 5555 5678',
      accountNumber: 'GN-456789',
    },
    internet: {
      provider: 'Telmex',
      phone: '800 123 4567',
      accountNumber: 'TEL-789012',
    },
  },
  documents: [
    {
      id: 'doc-1',
      name: 'Contrato de arrendamiento',
      type: 'contract',
      url: '/documents/contrato.pdf',
      uploadDate: '2024-01-15',
      status: 'approved',
    },
    {
      id: 'doc-2',
      name: 'Inventario inicial',
      type: 'inventory',
      url: '/documents/inventario.pdf',
      uploadDate: '2024-01-15',
      status: 'approved',
    },
  ],
  status: 'active',
}

// Conversaciones de ejemplo
export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participants: ['user-1', 'user-4'],
    lastMessage: 'Claro, te envio los documentos manana',
    lastMessageDate: '2024-05-05T14:30:00',
    unreadCount: 2,
    propertyId: 'prop-1',
  },
  {
    id: 'conv-2',
    participants: ['user-1', 'user-3'],
    lastMessage: 'Ya realice el deposito de este mes',
    lastMessageDate: '2024-05-04T10:15:00',
    unreadCount: 0,
    propertyId: 'prop-5',
  },
  {
    id: 'conv-3',
    participants: ['user-2', 'user-4'],
    lastMessage: 'Perfecto, nos vemos el jueves para la visita',
    lastMessageDate: '2024-05-03T16:45:00',
    unreadCount: 1,
    propertyId: 'prop-2',
  },
  {
    id: 'conv-4',
    participants: ['user-3', 'user-4'],
    lastMessage: 'El plomero pasara manana entre 10 y 12',
    lastMessageDate: '2024-05-02T09:20:00',
    unreadCount: 0,
    propertyId: 'prop-5',
  },
]

// Mensajes de ejemplo
export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'user-4',
    receiverId: 'user-1',
    content: 'Buenos dias, le escribo para informarle sobre el estado de su propiedad',
    read: true,
    createdAt: '2024-05-05T14:00:00',
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'user-1',
    receiverId: 'user-4',
    content: 'Hola Ana, gracias por el seguimiento. Como va todo?',
    read: true,
    createdAt: '2024-05-05T14:15:00',
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    senderId: 'user-4',
    receiverId: 'user-1',
    content: 'Todo muy bien, el inquilino esta al corriente con los pagos. Necesito enviarle los documentos actualizados',
    read: true,
    createdAt: '2024-05-05T14:20:00',
  },
  {
    id: 'msg-4',
    conversationId: 'conv-1',
    senderId: 'user-1',
    receiverId: 'user-4',
    content: 'Claro, te envio los documentos manana',
    read: false,
    createdAt: '2024-05-05T14:30:00',
  },
]

// Ganancias de propiedades (para inversionistas)
export const mockPropertyEarnings: PropertyEarnings[] = [
  {
    propertyId: 'prop-5',
    totalEarnings: 540000,
    monthlyEarnings: 45000,
    occupancyRate: 100,
    lastPaymentDate: '2024-05-05',
    nextPaymentDate: '2024-06-05',
    paymentHistory: [
      { month: '2024-05', amount: 45000, status: 'paid' },
      { month: '2024-04', amount: 45000, status: 'paid' },
      { month: '2024-03', amount: 45000, status: 'paid' },
      { month: '2024-02', amount: 45000, status: 'paid' },
      { month: '2024-01', amount: 45000, status: 'paid' },
    ],
  },
  {
    propertyId: 'prop-1',
    totalEarnings: 0,
    monthlyEarnings: 0,
    occupancyRate: 0,
    paymentHistory: [],
  },
]

// Funciones auxiliares
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('es-MX', {
    style: 'currency',
    currency: 'MXN',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

export function formatDate(date: string): string {
  return new Date(date).toLocaleDateString('es-MX', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
}

export function formatShortDate(date: string): string {
  return new Date(date).toLocaleDateString('es-MX', {
    day: 'numeric',
    month: 'short',
  })
}

// Campanas publicitarias de ejemplo
export const mockCampaigns: Campaign[] = [
  // Campanas activas
  {
    id: 'camp-1',
    propertyId: 'prop-6',
    ownerId: 'user-1',
    type: 'rent',
    status: 'active',
    budget: 15000,
    spentBudget: 8500,
    remainingBudget: 6500,
    leadsCount: 23,
    startDate: '2024-04-15',
    endDate: '2024-05-30',
    durationDays: 45,
    platform: ['Facebook', 'Instagram'],
    createdAt: '2024-04-14',
  },
  {
    id: 'camp-2',
    propertyId: 'prop-7',
    ownerId: 'user-1',
    type: 'sale',
    status: 'active',
    budget: 35000,
    spentBudget: 12000,
    remainingBudget: 23000,
    leadsCount: 15,
    startDate: '2024-05-01',
    endDate: '2024-06-30',
    durationDays: 60,
    platform: ['Facebook', 'Instagram', 'Google Ads'],
    createdAt: '2024-04-30',
  },
  {
    id: 'camp-3',
    propertyId: 'prop-9',
    ownerId: 'user-1',
    type: 'sale',
    status: 'paused',
    budget: 50000,
    spentBudget: 28000,
    remainingBudget: 22000,
    leadsCount: 31,
    startDate: '2024-03-15',
    endDate: '2024-06-15',
    durationDays: 90,
    platform: ['Facebook', 'Instagram', 'Google Ads', 'Portal Inmuebles24'],
    createdAt: '2024-03-14',
  },
  {
    id: 'camp-4',
    propertyId: 'prop-10',
    ownerId: 'user-1',
    type: 'rent',
    status: 'active',
    budget: 20000,
    spentBudget: 5000,
    remainingBudget: 15000,
    leadsCount: 12,
    startDate: '2024-05-10',
    endDate: '2024-06-25',
    durationDays: 45,
    platform: ['Facebook', 'Airbnb Ads'],
    createdAt: '2024-05-09',
  },
  // Campanas terminadas
  {
    id: 'camp-5',
    propertyId: 'prop-5',
    ownerId: 'user-1',
    type: 'rent',
    status: 'completed',
    budget: 12000,
    spentBudget: 12000,
    remainingBudget: 0,
    leadsCount: 45,
    startDate: '2023-11-01',
    endDate: '2023-12-15',
    durationDays: 44,
    result: 'rented',
    platform: ['Facebook', 'Instagram'],
    createdAt: '2023-10-31',
  },
  {
    id: 'camp-6',
    propertyId: 'prop-8',
    ownerId: 'user-1',
    type: 'rent',
    status: 'completed',
    budget: 8000,
    spentBudget: 6500,
    remainingBudget: 1500,
    leadsCount: 28,
    startDate: '2023-09-15',
    endDate: '2023-10-30',
    durationDays: 45,
    result: 'rented',
    platform: ['Facebook', 'Instagram'],
    createdAt: '2023-09-14',
  },
  {
    id: 'camp-7',
    propertyId: 'prop-1',
    ownerId: 'user-1',
    type: 'sale',
    status: 'cancelled',
    budget: 25000,
    spentBudget: 10000,
    remainingBudget: 15000,
    leadsCount: 8,
    startDate: '2023-06-01',
    endDate: '2023-07-15',
    durationDays: 44,
    result: 'cancelled',
    platform: ['Facebook', 'Google Ads'],
    createdAt: '2023-05-31',
  },
  {
    id: 'camp-8',
    propertyId: 'prop-6',
    ownerId: 'user-1',
    type: 'rent',
    status: 'completed',
    budget: 10000,
    spentBudget: 10000,
    remainingBudget: 0,
    leadsCount: 35,
    startDate: '2023-07-01',
    endDate: '2023-08-15',
    durationDays: 45,
    result: 'not_achieved',
    platform: ['Facebook'],
    createdAt: '2023-06-30',
  },
  {
    id: 'camp-9',
    propertyId: 'prop-9',
    ownerId: 'user-1',
    type: 'sale',
    status: 'completed',
    budget: 40000,
    spentBudget: 38000,
    remainingBudget: 2000,
    leadsCount: 52,
    startDate: '2023-12-01',
    endDate: '2024-02-28',
    durationDays: 89,
    result: 'not_achieved',
    platform: ['Facebook', 'Instagram', 'Google Ads', 'Portal Inmuebles24'],
    createdAt: '2023-11-30',
  },
]
