import { Platform, StyleSheet } from 'react-native'

const serifFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'serif',
})

export const registerOwnerWelcomeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fefbf6',
  },
  backButton: {
    position: 'absolute',
    left: 43,
    top: 43,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingTop: 65,
    paddingBottom: 40,
  },
  main: {
    width: '100%',
    alignItems: 'center',
    gap: 17,
  },
  header: {
    width: 341,
    alignItems: 'center',
    gap: 20,
  },
  logoWrap: {
    alignItems: 'center',
  },
  heroCopy: {
    width: 340,
    alignItems: 'center',
    gap: 16,
  },
  title: {
    color: '#155721',
    fontFamily: serifFont,
    fontSize: 40,
    fontWeight: '700',
    lineHeight: 40,
    textAlign: 'center',
  },
  subtitle: {
    width: 310,
    color: '#000000',
    fontSize: 13,
    lineHeight: 20,
    letterSpacing: 0.65,
    textAlign: 'center',
  },
  featuresRow: {
    width: 392,
    height: 84,
    flexDirection: 'row',
    gap: 7,
    marginTop: 14,
  },
  featureCard: {
    flex: 1,
    height: 84,
    borderWidth: 1,
    borderColor: '#e5dfd2',
    borderRadius: 12,
    backgroundColor: '#fffef9',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
  },
  featureIcon: {
    width: 35,
    height: 35,
    marginBottom: 8,
  },
  featureLabel: {
    color: '#1e2d29',
    fontSize: 8,
    fontWeight: '600',
    lineHeight: 10,
    textAlign: 'center',
  },
  featureLabelSmall: {
    fontSize: 7,
    lineHeight: 9,
  },
  imageSection: {
    width: '100%',
    alignItems: 'center',
    marginTop: 31,
  },
  teamImage: {
    width: 440,
    height: 273,
    borderRadius: 12,
  },
  messageCard: {
    width: 359,
    minHeight: 83,
    marginTop: -44,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e4e4e4',
    borderRadius: 12,
    backgroundColor: '#faf6f0',
    paddingVertical: 10,
    paddingLeft: 7,
    paddingRight: 10,
    gap: 19,
    shadowColor: '#e2dbd1',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 3.65,
    elevation: 3,
  },
  messageIcon: {
    width: 44,
    height: 45,
  },
  messageText: {
    flex: 1,
    color: '#000000',
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0.7,
  },
  continueButton: {
    width: 304,
    height: 45,
    marginTop: 42,
    borderRadius: 12,
    backgroundColor: '#013f2f',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 25,
    position: 'relative',
  },
  continueButtonText: {
    color: '#ffffff',
    fontSize: 15,
    lineHeight: 16,
    textAlign: 'center',
  },
  continueIcon: {
    position: 'absolute',
    right: 24,
  },
})
