import { Platform, StyleSheet } from 'react-native'

const serifFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'serif',
})

export const registerOwnerFinalStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fefbf6',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 30,
    paddingTop: 56,
    paddingBottom: 40,
  },
  main: {
    width: '100%',
    maxWidth: 371,
    gap: 24,
  },
  top: {
    width: '100%',
    gap: 14,
  },
  logoWrap: {
    alignItems: 'center',
    marginBottom: 11,
  },
  progressRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  progressLabel: {
    color: '#e4ac73',
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 17,
  },
  progressTrack: {
    flex: 1,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#ddd5c6',
  },
  progressActive: {
    width: '100%',
    height: 2,
    borderRadius: 2,
    backgroundColor: '#c2824b',
  },
  headerCopy: {
    width: '100%',
    alignItems: 'center',
    gap: 1,
  },
  title: {
    width: '100%',
    color: '#155721',
    fontFamily: serifFont,
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 40,
    textAlign: 'center',
    letterSpacing: 0.32,
  },
  subtitle: {
    width: 310,
    color: '#000000',
    fontSize: 13,
    lineHeight: 20,
    letterSpacing: 0.65,
    textAlign: 'center',
  },
  formArea: {
    width: '100%',
    gap: 18,
  },
  optionSection: {
    width: '100%',
    gap: 19,
  },
  sectionTitle: {
    color: '#11451a',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: -0.16,
  },
  chipsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  chip: {
    height: 42,
    borderWidth: 1,
    borderColor: '#bf8638',
    borderRadius: 12,
    backgroundColor: '#fdfaf5',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  chipSelected: {
    backgroundColor: '#fff1df',
    borderColor: '#013f2f',
  },
  chipText: {
    color: '#000000',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 16,
    letterSpacing: -0.13,
    textAlign: 'center',
  },
  notesSection: {
    width: '100%',
    gap: 15,
  },
  notesIntro: {
    width: 262,
    alignItems: 'center',
    gap: 10,
  },
  notesTitle: {
    width: '100%',
    color: '#11451a',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: -0.16,
    textAlign: 'center',
  },
  notesSubtitle: {
    width: '100%',
    color: '#6c6962',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 20,
    letterSpacing: -0.16,
  },
  notesBox: {
    width: 355,
    minHeight: 96,
    borderWidth: 1,
    borderColor: '#d9d3d3',
    borderRadius: 12,
    backgroundColor: '#fdfcf8',
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 22,
    textAlignVertical: 'top',
    color: '#1e2d29',
    fontSize: 14,
    lineHeight: 19,
  },
  counter: {
    position: 'absolute',
    right: 16,
    bottom: 8,
    color: '#414040',
    fontSize: 12,
    lineHeight: 13,
  },
  notesBoxWrap: {
    position: 'relative',
    width: 355,
  },
  trustCard: {
    width: '100%',
    minHeight: 65,
    borderWidth: 1,
    borderColor: '#e4e4e4',
    borderRadius: 12,
    backgroundColor: '#faf6f0',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingLeft: 7,
    paddingRight: 10,
    gap: 19,
    shadowColor: '#e2dbd1',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 1,
    shadowRadius: 3.65,
    elevation: 3,
  },
  trustDot: {
    width: 44,
    height: 45,
    borderRadius: 100,
    backgroundColor: '#fbecd9',
  },
  trustText: {
    flex: 1,
    color: '#000000',
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0.7,
  },
  errorText: {
    color: '#b42318',
    fontSize: 12,
    lineHeight: 17,
    textAlign: 'center',
  },
  finishButton: {
    alignSelf: 'center',
    width: 267,
    height: 50,
    borderRadius: 12,
    backgroundColor: '#013f2f',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 36,
    paddingHorizontal: 20,
  },
  finishButtonDisabled: {
    opacity: 0.62,
  },
  finishButtonText: {
    color: '#fdfcf8',
    fontSize: 15,
    lineHeight: 16,
    textAlign: 'center',
  },
})
