import { Platform, StyleSheet } from 'react-native'

const numberFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'serif',
})

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  content: {
    paddingHorizontal: 11,
    paddingTop: 42,
    paddingBottom: 96,
  },
  logoWrap: {
    alignItems: 'center',
    marginBottom: 12,
  },
  topRow: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  roleLabel: {
    color: '#315b41',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 6,
  },
  datePill: {
    height: 18,
    borderRadius: 5,
    backgroundColor: '#c9af6f',
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '600',
  },
  profileRow: {
    marginTop: -14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 5,
  },
  profileLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    position: 'relative',
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 28,
    backgroundColor: '#d8ba78',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  avatarText: {
    color: '#24442f',
    fontSize: 16,
    fontWeight: '800',
  },
  profileMenu: {
    position: 'absolute',
    left: 64,
    top: 8,
    minWidth: 172,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eadbc8',
    padding: 6,
    gap: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 20,
  },
  profileMenuButton: {
    minHeight: 34,
    borderRadius: 6,
    backgroundColor: '#fff8ef',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 10,
  },
  profileMenuButtonText: {
    color: '#315b41',
    fontSize: 12,
    fontWeight: '700',
  },
  profileLogoutButton: {
    minHeight: 34,
    borderRadius: 6,
    backgroundColor: '#315b41',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 10,
  },
  profileLogoutText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  greeting: {
    color: '#232323',
    fontFamily: "cormorant",
    fontSize: 25,
    lineHeight: 30,
  },
  helper: {
    color: '#8d8d8d',
    fontSize: 12,
    lineHeight: 16,
  },
  notification: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  heroCards: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 12,
  },
  availableCard: {
    width: 148,
    height: 104,
    borderRadius: 9,
    backgroundColor: '#3d5f42',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  spacedLabel: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 5,
  },
  availableValue: {
    color: '#d4b66f',
    fontFamily: "cormorant",
    fontSize: 50,
    lineHeight: 48,
  },
  earningsCard: {
    flex: 1,
    height: 104,
    borderRadius: 10,
    backgroundColor: '#f9f3ef',
    borderWidth: 1,
    borderColor: '#e0d5cf',
    paddingTop: 5,
    paddingHorizontal: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 3,
    gap: 4,
  },
  earningsLabel: {
    color: '#bf7634',
    fontSize: 12,
    textAlign: 'center',
    letterSpacing: 1.3,
  },
  earningsValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  earningsValue: {
    color: '#20252b',
    fontFamily: numberFont,
    fontSize: 39,
    lineHeight: 43,
  },
  currency: {
    color: '#20252b',
    fontSize: 12,
    marginBottom: 9,
    marginLeft: 4,

  },
  earningsCaption: {
    color: '#8a817e',
    fontSize: 13,
    textAlign: 'center',
    marginTop: -2,
  },
  earningsLink: {
    color: '#c77731',
    fontSize: 10,
    textAlign: 'right',
    marginTop: 2,
  },
  listedButton: {
    marginTop: 8,
    height: 58,
    borderRadius: 9,
    backgroundColor: '#f9f3ef',
    borderWidth: 1,
    borderColor: '#e0d5cf',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    gap:8,
  },
  listedIcon: {
    width: 34,
    alignItems: 'center',
  },
  listedCopy: {
    flex: 1,
  },
  listedTitle: {
    color: '#2a2d31',
    fontSize: 13,
    fontWeight: '700',
  },
  listedMeta: {
    color: '#2a2d31',
    fontSize: 14,
    marginTop: 2,
  },
  sectionTitle: {
    color: '#006b43',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 13,
    marginBottom: 8,
  },
  sectionHeader: {
    marginTop: 3,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionHeaderTitle: {
    color: '#006b43',
    fontSize: 15,
    fontWeight: '700',
  },
  sectionAction: {
    color: '#006b43',
    fontSize: 12,
    fontWeight: '700',
  },
  prioritiesRow: {
    flexDirection: 'row',
    gap: 7,
  },
  priorityCard: {
    flex: 1,
    height: 85,
    borderRadius: 8,
    backgroundColor: '#3d5f42',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    gap: 2,
  },
  priorityValue: {
    color: '#ffffff',
    fontFamily: numberFont,
    fontSize: 27,
    lineHeight: 29,
  },
  priorityValueGold: {
    color: '#d4b66f',
  },
  priorityLabel: {
    color: '#ffffff',
    fontSize: 10,
    lineHeight: 10,
    textAlign: 'center',
  },
  goalsRow: {
    flexDirection: 'row',
    gap: 6,
  },
  goalCard: {
    flex: 1,
    minHeight: 78,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e4e4',
    padding: 7,
  },
  goalTitle: {
    color: '#006b43',
    fontSize: 8,
    fontWeight: '700',
    marginBottom: 5,
  },
  goalValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  goalValue: {
    color: '#2a2d31',
    fontSize: 17,
  },
  goalUnit: {
    color: '#2a2d31',
    fontSize: 11,
    marginLeft: 4,
    marginBottom: 2,
  },
  progressTrack: {
    height: 11,
    borderRadius: 5,
    backgroundColor: '#d9d9d9',
    overflow: 'hidden',
    marginTop: 8,
  },
  progressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: '#007543',
  },
  goalCaption: {
    color: '#8a817e',
    fontSize: 8,
    marginTop: 3,
  },
  panel: {
    borderRadius: 9,
    backgroundColor: '#fffdfc',
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.16,
    shadowRadius: 5,
    elevation: 4,
  },
  appointmentsPanel: {
    paddingBottom: 12,
    marginTop: 12,
  },
  appointmentList: {
    gap: 4,
  },
  appointmentCard: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: '#3d5f42',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 7,
  },
  appointmentCopy: {
    flex: 1,
    minWidth: 0,
  },
  appointmentTitle: {
    color: '#d4b66f',
    fontSize: 12,
    fontWeight: '700',
  },
  appointmentMeta: {
    color: '#ffffff',
    fontSize: 9,
    marginTop: 2,
  },
  appointmentDate: {
    width: 98,
    borderLeftWidth: 1,
    borderLeftColor: '#d8c596',
    paddingLeft: 8,
    marginLeft: 8,
  },
  dayPill: {
    alignSelf: 'flex-start',
    minHeight: 16,
    borderRadius: 4,
    backgroundColor: '#d4b66f',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 5,
  },
  appointmentDay: {
    color: '#ffffff',
    fontSize: 8,
    fontWeight: '700',
  },
  appointmentTime: {
    color: '#d4b66f',
    fontSize: 10,
    marginTop: 2,
    textAlign: 'center',
  },
  statusPill: {
    alignSelf: 'center',
    width: 67,
    height: 12,
    borderRadius: 2,
    backgroundColor: '#ffffff',
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusText: {
    color: '#3d5f42',
    fontSize: 7,
  },
  centerButton: {
    alignSelf: 'center',
    marginTop: 10,
    height: 33,
    flex: 1,
    minWidth: 0,
    borderRadius: 5,
    backgroundColor: '#c89c4c',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 16,
  },
  centerButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  appointmentActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  googleCalendarSettings: {
    marginTop: 10,
    borderRadius: 7,
    backgroundColor: '#f8f2ee',
    padding: 10,
  },
  calendarSettingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 8,
  },
  calendarSettingsTitle: {
    flex: 1,
    color: '#3d5a40',
    fontSize: 13,
    fontWeight: '700',
  },
  calendarSmallButton: {
    minWidth: 78,
    height: 25,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  calendarSmallButtonText: {
    color: '#0c6740',
    fontSize: 10,
    fontWeight: '600',
  },
  calendarSettingsEmpty: {
    color: '#737373',
    fontSize: 11,
    lineHeight: 15,
    textAlign: 'center',
    paddingVertical: 10,
  },
  calendarList: {
    gap: 6,
  },
  calendarOptionRow: {
    minHeight: 42,
    borderRadius: 6,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  calendarToggle: {
    width: 42,
    height: 24,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarToggleActive: {
    backgroundColor: '#3d5a40',
    borderColor: '#3d5a40',
  },
  calendarToggleText: {
    color: '#737373',
    fontSize: 9,
    fontWeight: '700',
  },
  calendarToggleTextActive: {
    color: '#ffffff',
  },
  calendarOptionCopy: {
    flex: 1,
    minWidth: 0,
  },
  calendarOptionTitle: {
    color: '#232323',
    fontSize: 11,
    fontWeight: '600',
  },
  calendarOptionMeta: {
    color: '#7e8b86',
    fontSize: 9,
    marginTop: 2,
  },
  calendarPrimaryButton: {
    minWidth: 52,
    height: 24,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#cbb375',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
  },
  calendarPrimaryButtonActive: {
    backgroundColor: '#cbb375',
  },
  calendarPrimaryButtonText: {
    color: '#3d5a40',
    fontSize: 9,
    fontWeight: '700',
  },
  calendarPrimaryButtonTextActive: {
    color: '#19191f',
  },
  calendarActionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginTop: 9,
  },
  calendarActionButton: {
    flex: 1,
    minHeight: 31,
    borderRadius: 6,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  calendarActionButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  calendarTestLabel: {
    color: '#3d5a40',
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 5,
  },
  calendarDestinationList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  calendarDestinationChip: {
    maxWidth: '48%',
    minHeight: 26,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    backgroundColor: '#fffcfc',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  calendarDestinationChipActive: {
    backgroundColor: '#3d5a40',
    borderColor: '#3d5a40',
  },
  calendarDestinationChipText: {
    color: '#3d5a40',
    fontSize: 9,
    fontWeight: '700',
  },
  calendarDestinationChipTextActive: {
    color: '#ffffff',
  },
  calendarTestInput: {
    minHeight: 34,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    color: '#232323',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 6,
    marginBottom: 6,
    backgroundColor: '#fffcfc',
  },
  calendarPicker: {
    marginBottom: 6,
  },
  calendarPickerValue: {
    minHeight: 34,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    color: '#232323',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 8,
    backgroundColor: '#fffcfc',
  },
  calendarPickerActions: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 6,
  },
  calendarPickerInput: {
    flex: 1,
    minHeight: 32,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#ded6ca',
    color: '#232323',
    fontSize: 11,
    paddingHorizontal: 9,
    paddingVertical: 6,
    backgroundColor: '#fffcfc',
  },
  calendarTestCreateButton: {
    minHeight: 32,
    borderRadius: 6,
    backgroundColor: '#3d5a40',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    marginTop: 2,
  },
  calendarTestCreateButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
  },
  appointmentModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(25, 25, 31, 0.42)',
    justifyContent: 'flex-end',
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  appointmentModalPanel: {
    maxHeight: '88%',
    borderRadius: 8,
    backgroundColor: '#fffcfc',
    padding: 12,
  },
  appointmentModalHeader: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 6,
  },
  appointmentModalTitle: {
    flex: 1,
    color: '#0c6740',
    fontSize: 17,
    fontWeight: '700',
  },
  appointmentModalClose: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: '#f1ebda',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appointmentModalBack: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: '#f1ebda',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appointmentModalContent: {
    paddingBottom: 6,
  },
  appointmentPickerButton: {
    minHeight: 48,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#ded6ca',
    backgroundColor: '#fffcfc',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  appointmentPickerCopy: {
    flex: 1,
    minWidth: 0,
  },
  appointmentPickerTitle: {
    color: '#3d5a40',
    fontSize: 12,
    fontWeight: '700',
  },
  appointmentPickerMeta: {
    color: '#7e8b86',
    fontSize: 10,
    marginTop: 2,
  },
  appointmentSelectionList: {
    gap: 8,
  },
  appointmentSelectionRow: {
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ded6ca',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  appointmentSelectionRowActive: {
    backgroundColor: '#3d5a40',
    borderColor: '#3d5a40',
  },
  appointmentSelectionRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  appointmentSelectionRowTitle: {
    color: '#232323',
    fontSize: 12,
    fontWeight: '700',
  },
  appointmentSelectionRowTitleActive: {
    color: '#ffffff',
  },
  appointmentSelectionRowMeta: {
    color: '#7e8b86',
    fontSize: 10,
    lineHeight: 14,
    marginTop: 3,
  },
  appointmentSelectionRowMetaActive: {
    color: '#ffffff',
  },
  quickPanel: {
    marginTop: 8,
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  quickButton: {
    width: '31.8%',
    minHeight: 38,
    borderRadius: 5,
    backgroundColor: '#fff8ef',
    borderWidth: 1,
    borderColor: '#eadbc8',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  quickText: {
    flex: 1,
    color: '#2a2d31',
    fontSize: 10,
    fontWeight: '700',
    marginLeft: 5,
  },
  leadPanel: {
    marginTop: 12,
  },
  panelSubtitle: {
    color: '#7b8780',
    fontSize: 10,
    marginTop: -4,
    marginBottom: 11,
  },
  metricGrid: {
    flexDirection: 'row',
    gap: 6,
  },
  metricCard: {
    flex: 1,
    minHeight: 77,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e4e4',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  metricValue: {
    color: '#2a2d31',
    fontFamily: numberFont,
    fontSize: 28,
    lineHeight: 32,
  },
  metricLabel: {
    color: '#7b8780',
    fontSize: 9,
    textAlign: 'center',
    lineHeight: 11,
  },
  subTitle: {
    color: '#006b43',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 7,
  },
  funnelRow: {
    minHeight: 72,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e4e4',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 6,
  },
  funnelItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  funnelValue: {
    color: '#2a2d31',
    fontFamily: numberFont,
    fontSize: 20,
  },
  funnelLabel: {
    color: '#7b8780',
    fontSize: 8,
    textAlign: 'center',
    lineHeight: 10,
  },
  alertRow: {
    height: 36,
    borderRadius: 5,
    backgroundColor: '#ffe1dd',
    borderWidth: 1,
    borderColor: '#ffc5bc',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
    gap: 8,
    marginTop: 6,
  },
  alertText: {
    flex: 1,
    color: '#4d4747',
    fontSize: 12,
  },
  outlineButton: {
    alignSelf: 'center',
    marginTop: 14,
    height: 32,
    minWidth: 127,
    borderRadius: 5,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dcdcdc',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
  },
  outlineButtonText: {
    color: '#006b43',
    fontSize: 12,
    fontWeight: '700',
  },
  campaignPanel: {
    marginTop: 12,
  },
  campaignMetricGrid: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 14,
  },
  campaignMetric: {
    flex: 1,
    minHeight: 77,
    borderRadius: 5,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  campaignValue: {
    fontFamily: numberFont,
    fontSize: 30,
    lineHeight: 34,
  },
  campaignLabel: {
    color: '#2a2d31',
    fontSize: 9,
    textAlign: 'center',
  },
  campaignList: {
    gap: 6,
  },
  campaignRow: {
    minHeight: 58,
    borderRadius: 7,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e1e1e1',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  campaignImage: {
    width: 77,
    height: 48,
    borderRadius: 6,
    marginRight: 7,
  },
  campaignCopy: {
    flex: 1,
    minWidth: 0,
  },
  campaignTitle: {
    color: '#2a2d31',
    fontSize: 10,
    fontWeight: '800',
  },
  campaignDates: {
    color: '#2a2d31',
    fontSize: 8,
    marginTop: 3,
  },
  campaignStatus: {
    alignSelf: 'flex-start',
    minHeight: 15,
    borderRadius: 3,
    paddingHorizontal: 6,
    justifyContent: 'center',
    marginTop: 5,
  },
  campaignStatusText: {
    fontSize: 8,
    fontWeight: '700',
  },
  remainingBox: {
    width: 78,
    alignItems: 'flex-end',
  },
  remainingLabel: {
    color: '#2a7a48',
    fontSize: 8,
    textAlign: 'right',
  },
  remainingValue: {
    color: '#2a7a48',
    fontSize: 12,
    marginTop: 2,
  },
})
