import { StyleSheet } from 'react-native'

import { borderRadius, spacing, typography } from '@/lib/theme'

import { advisorTheme } from '../theme'

export const styles = StyleSheet.create({
  stepContent: {
    gap: spacing.md,
  },
  stepQuestion: {
    fontSize: typography.h3.fontSize,
    fontWeight: '700',
    color: advisorTheme.text,
    marginBottom: spacing.sm,
  },
  stepHint: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.textMuted,
    marginTop: -spacing.sm,
    marginBottom: spacing.sm,
  },
  inputGroup: {
    gap: spacing.xs,
  },
  inputLabel: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
    marginBottom: 4,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    height: 48,
    gap: spacing.sm,
  },
  inputField: {
    flex: 1,
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
  },
  inputPrefix: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.textMuted,
  },
  inputHint: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
    fontStyle: 'italic',
    marginTop: 4,
  },
  textArea: {
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  propertyTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  propertyTypeCard: {
    width: '48%',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
    position: 'relative',
  },
  propertyTypeCardActive: {
    borderColor: advisorTheme.accent,
    backgroundColor: advisorTheme.accent + '10',
  },
  propertyTypeLabel: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
    marginTop: spacing.sm,
  },
  propertyTypeLabelActive: {
    color: advisorTheme.accent,
    fontWeight: '600',
  },
  propertyTypeCheck: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: advisorTheme.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  detailItem: {
    width: '48%',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    alignItems: 'center',
    gap: spacing.xs,
  },
  detailLabel: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
  },
  detailInput: {
    fontSize: typography.h3.fontSize,
    fontWeight: '700',
    color: advisorTheme.text,
    textAlign: 'center',
    width: '100%',
  },
  togglesContainer: {
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  toggleOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    gap: spacing.md,
  },
  toggleOptionActive: {
    backgroundColor: advisorTheme.accent + '15',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: borderRadius.sm,
    borderWidth: 2,
    borderColor: advisorTheme.textMuted,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxActive: {
    backgroundColor: advisorTheme.accent,
    borderColor: advisorTheme.accent,
  },
  toggleLabel: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  amenityChip: {
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: advisorTheme.border,
  },
  amenityChipActive: {
    backgroundColor: advisorTheme.accent + '20',
    borderColor: advisorTheme.accent,
  },
  amenityChipText: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
  },
  amenityChipTextActive: {
    color: advisorTheme.accent,
    fontWeight: '500',
  },
  measurementsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  measurementItem: {
    width: '48%',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    padding: spacing.md,
  },
  measurementLabel: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
    marginBottom: spacing.xs,
  },
  measurementInput: {
    fontSize: typography.h4.fontSize,
    fontWeight: '600',
    color: advisorTheme.text,
  },
  uploadArea: {
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.lg,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: advisorTheme.border,
    padding: spacing.xl,
    alignItems: 'center',
    gap: spacing.sm,
  },
  uploadText: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
    fontWeight: '500',
  },
  uploadHint: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
  },
  photosPreview: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  photoItem: {
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    padding: spacing.sm,
  },
  photoName: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
  },
  priceInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    paddingLeft: spacing.md,
    height: 56,
  },
  priceInputLarge: {
    flex: 1,
    fontSize: typography.h3.fontSize,
    fontWeight: '600',
    color: advisorTheme.text,
  },
  currencySymbol: {
    fontSize: typography.h4.fontSize,
    color: advisorTheme.textMuted,
    marginRight: spacing.xs,
  },
  currencyToggle: {
    flexDirection: 'row',
    borderLeftWidth: 1,
    borderLeftColor: advisorTheme.border,
  },
  currencyBtn: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  currencyBtnActive: {
    backgroundColor: advisorTheme.accent + '20',
  },
  currencyBtnText: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.textMuted,
  },
  currencyBtnTextActive: {
    color: advisorTheme.accent,
    fontWeight: '600',
  },
  sectionDivider: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: advisorTheme.accent,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  commissionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  commissionItem: {
    flex: 1,
  },
  commissionLabel: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
    marginBottom: 4,
  },
  commissionInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.sm,
    height: 44,
  },
  commissionField: {
    flex: 1,
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.md,
    height: 48,
    gap: spacing.sm,
  },
  searchInput: {
    flex: 1,
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
  },
  contactMethodRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  contactMethodBtn: {
    flex: 1,
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: advisorTheme.border,
  },
  contactMethodBtnActive: {
    backgroundColor: advisorTheme.accent + '20',
    borderColor: advisorTheme.accent,
  },
  contactMethodText: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
  },
  contactMethodTextActive: {
    color: advisorTheme.accent,
    fontWeight: '600',
  },
  summaryCard: {
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
  },
  summaryLabel: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.textMuted,
  },
  summaryValue: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: advisorTheme.text,
    textAlign: 'right',
    flex: 1,
    marginLeft: spacing.md,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: advisorTheme.border,
    marginVertical: spacing.sm,
  },
  documentsAccordion: {
    gap: spacing.sm,
  },
  documentAccordionItem: {
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.lg,
    overflow: 'hidden',
  },
  documentAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  documentAccordionHeaderExpanded: {
    borderBottomWidth: 1,
    borderBottomColor: advisorTheme.border,
  },
  documentAccordionHeaderWithFile: {
    backgroundColor: advisorTheme.accent + '15',
  },
  documentAccordionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: spacing.sm,
  },
  documentCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: advisorTheme.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  documentCheckboxActive: {
    backgroundColor: advisorTheme.accent,
    borderColor: advisorTheme.accent,
  },
  documentAccordionInfo: {
    flex: 1,
  },
  documentAccordionLabel: {
    fontSize: typography.body.fontSize,
    fontWeight: '500',
    color: advisorTheme.text,
  },
  documentRequiredTag: {
    fontSize: 10,
    color: advisorTheme.error,
    fontWeight: '600',
    marginTop: 2,
  },
  documentFileName: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.accent,
    marginTop: 2,
  },
  documentAccordionContent: {
    padding: spacing.md,
    backgroundColor: advisorTheme.surfaceLight,
  },
  documentUploadArea: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: advisorTheme.border,
    borderRadius: borderRadius.md,
    gap: spacing.xs,
  },
  documentUploadText: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: advisorTheme.accent,
  },
  documentUploadHint: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
  },
  documentFilePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  documentFileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flex: 1,
  },
  documentFileDetails: {
    flex: 1,
  },
  documentFileNameLarge: {
    fontSize: typography.body.fontSize,
    fontWeight: '500',
    color: advisorTheme.text,
  },
  documentFileStatus: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.success,
    marginTop: 2,
  },
  documentFileActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  documentChangeBtn: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    backgroundColor: advisorTheme.surface,
    borderRadius: borderRadius.sm,
  },
  documentChangeBtnText: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.accent,
    fontWeight: '600',
  },
  documentRemoveBtn: {
    padding: spacing.xs,
  },
  additionalFilesSection: {
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: advisorTheme.border,
  },
  additionalFilesTitle: {
    fontSize: typography.body.fontSize,
    fontWeight: '600',
    color: advisorTheme.text,
  },
  additionalFilesHint: {
    fontSize: typography.caption.fontSize,
    color: advisorTheme.textMuted,
    marginTop: 4,
    marginBottom: spacing.md,
  },
  additionalFilesList: {
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  additionalFileItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: advisorTheme.surface,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
  },
  additionalFileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  additionalFileItemName: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.text,
  },
  uploadAdditionalBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: advisorTheme.accent,
    borderRadius: borderRadius.md,
    borderStyle: 'dashed',
  },
  uploadAdditionalBtnText: {
    fontSize: typography.body.fontSize,
    color: advisorTheme.accent,
    fontWeight: '500',
  },
})
