import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  container: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 28,
    paddingBottom: 78,
  },
  title: {
    color: '#3D5A40',
    fontSize: 26,
    lineHeight: 31,
    fontWeight: '600',
  },
  subtitle: {
    marginTop: 4,
    color: '#717171',
    fontSize: 13,
    lineHeight: 18,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
  },
  summaryTile: {
    flex: 1,
    minWidth: 0,
    height: 64,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#e1d8cb',
    backgroundColor: '#fbf8f2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  summaryValue: {
    color: '#0c6740',
    fontSize: 19,
    lineHeight: 23,
    fontWeight: '700',
  },
  summaryLabel: {
    marginTop: 2,
    color: '#717171',
    fontSize: 10,
    lineHeight: 13,
  },
  searchRow: {
    height: 43,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#d6cec3',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    marginTop: 14,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    color: '#19191f',
    fontSize: 13,
    padding: 0,
  },
  errorBox: {
    marginTop: 12,
    borderRadius: 8,
    backgroundColor: '#fff0ee',
    padding: 11,
  },
  errorText: {
    color: '#a13b2f',
    fontSize: 12,
    lineHeight: 16,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: {
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  listContent: {
    paddingTop: 14,
    paddingBottom: 28,
  },
  screenHeader: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#f3eee6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  screenHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  advisorCard: {
    minHeight: 82,
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  advisorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
  },
  advisorAvatarText: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '700',
  },
  advisorCardBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 11,
  },
  advisorContact: {
    marginTop: 3,
    color: '#9a9084',
    fontSize: 11,
    lineHeight: 14,
  },
  advisorHeader: {
    minHeight: 54,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#e1d8cb',
    backgroundColor: '#fbf8f2',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    marginBottom: 9,
  },
  advisorHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  advisorName: {
    color: '#3D5A40',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '700',
  },
  advisorMeta: {
    marginTop: 3,
    color: '#717171',
    fontSize: 11,
    lineHeight: 14,
  },
  advisorCountBadge: {
    minWidth: 34,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#0c6740',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  advisorCountText: {
    color: '#ffffff',
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '700',
  },
  leadSeparator: {
    height: 9,
  },
  sectionSeparator: {
    height: 16,
  },
  separator: {
    height: 9,
  },
  leadCard: {
    minHeight: 82,
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 11,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  leadAvatar: {
    width: 42,
    height: 42,
    borderRadius: 9,
    backgroundColor: '#f1eadf',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leadAvatarText: {
    color: '#0c6740',
    fontSize: 17,
    fontWeight: '700',
  },
  leadBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 11,
  },
  leadName: {
    color: '#19191f',
    fontSize: 15,
    lineHeight: 19,
    fontWeight: '600',
  },
  leadMeta: {
    marginTop: 3,
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 14,
  },
  leadProperty: {
    marginTop: 3,
    color: '#717171',
    fontSize: 11,
    lineHeight: 14,
  },
  leadDetailCard: {
    minHeight: 70,
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#fbf8f2',
    justifyContent: 'center',
    paddingHorizontal: 12,
    marginTop: 14,
  },
  leadDetailTitle: {
    color: '#3D5A40',
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '700',
  },
  leadDetailMeta: {
    marginTop: 4,
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  emptyState: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  emptyStateText: {
    color: '#717171',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.22)',
    justifyContent: 'flex-end',
  },
  followPanel: {
    maxHeight: '78%',
    minHeight: 360,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    backgroundColor: '#ffffff',
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 24,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  modalTitle: {
    color: '#19191f',
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '700',
  },
  modalSubtitle: {
    marginTop: 3,
    color: '#717171',
    fontSize: 12,
    lineHeight: 16,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3eee6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followLoadingState: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  followErrorText: {
    marginTop: 24,
    color: '#a13b2f',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  emptyFollowState: {
    minHeight: 240,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  followListContent: {
    paddingTop: 16,
    paddingBottom: 10,
  },
  followCard: {
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#fbf8f2',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  followIcon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: '#efe6d8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followBody: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  followDate: {
    color: '#0c6740',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  followNotes: {
    marginTop: 4,
    color: '#19191f',
    fontSize: 13,
    lineHeight: 18,
  },
  nextActionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 8,
  },
  nextActionText: {
    flex: 1,
    minWidth: 0,
    color: '#717171',
    fontSize: 11,
    lineHeight: 15,
  },
  followDetailCard: {
    borderRadius: 9,
    borderWidth: 0.5,
    borderColor: '#ded5c8',
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: 16,
  },
  detailRow: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#eee5d9',
    paddingVertical: 10,
  },
  detailLabel: {
    color: '#0c6740',
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  detailValue: {
    marginTop: 3,
    color: '#19191f',
    fontSize: 13,
    lineHeight: 18,
  },
})
