import { Platform, StyleSheet } from 'react-native'

const serifFont = Platform.select({
  ios: 'Georgia',
  android: 'serif',
  default: 'serif',
})

export const registerNewStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#fefbf6',
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 17,
    paddingTop: 46,
    paddingBottom: 40,
  },
  topBar: {
    width: '100%',
    maxWidth: 407,
    minHeight: 78,
    justifyContent: 'center',
    marginBottom: 16,
  },
  backButton: {
    position: 'absolute',
    left: 0,
    top: 0,
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
  },
  backButtonText: {
    color: '#204c31',
    fontSize: 14,
    lineHeight: 20,
  },
  logo: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    width: 326,
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    color: '#214c31',
    fontFamily: serifFont,
    fontSize: 35,
    fontWeight: '400',
    lineHeight: 42,
    textAlign: 'center',
    letterSpacing: -1.6,
  },
  subtitle: {
    marginTop: 13,
    color: '#737373',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.98,
    textAlign: 'center',
  },
  options: {
    width: '100%',
    maxWidth: 407,
    gap: 20,
    paddingHorizontal: 10,
    paddingTop: 10,
  },
  optionCard: {
    width: '100%',
    minHeight: 102,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#f0e8e1',
    borderRadius: 12,
    backgroundColor: '#fdf9f6',
    paddingLeft: 11,
    paddingRight: 14,
    paddingBottom: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.22,
    shadowRadius: 2.15,
    elevation: 3,
  },
  optionDot: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: '#f3ede6',
    marginRight: 11,
  },
  optionCopy: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingTop: 6,
  },
  optionTitle: {
    color: '#204c31',
    fontFamily: serifFont,
    fontSize: 25,
    fontWeight: '400',
    lineHeight: 34,
    letterSpacing: -1.28,
  },
  optionDescription: {
    marginTop: 3,
    color: '#737373',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.98,
  },
  optionArrow: {
    width: 32,
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginLeft: 8,
  },
})
