import type { BackendLeadV2FollowingRecord } from "@/lib/api";

const MOCK_LEAD_ID = "mock-lead-001";

function mockImage(id: string, filename: string) {
  return {
    _id: `mock-attachment-${id}`,
    filename,
    mime: "image/jpeg",
    size: 180_000,
    url: `https://picsum.photos/seed/lead-following-${id}/900/600`,
  };
}

/** Datos de prueba para la pantalla de historial de seguimientos. */
export const mockFollowings: BackendLeadV2FollowingRecord[] = [
  {
    id: "mock-following-01",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "Primer contacto realizado por WhatsApp. El cliente busca una casa de tres recámaras.",
    contactSummary: "Interesado en conocer opciones de venta.",
    nextAction: "Enviar catálogo de propiedades disponibles.",
    attachments: [],
    createdAt: "2026-09-01T09:15:00.000Z",
  },
  {
    id: "mock-following-02",
    leadId: MOCK_LEAD_ID,
    authorType: "coordinator",
    authorId: "mock-coordinator-01",
    text: "Se compartió la primera propuesta de distribución y acabados.",
    contactSummary: "Pidió revisar las fotografías con su pareja.",
    attachments: [mockImage("02", "propuesta-sala.jpg")],
    createdAt: "2026-09-01T12:40:00.000Z",
  },
  {
    id: "mock-following-03",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "",
    attachments: [mockImage("03", "fachada-propiedad.jpg")],
    createdAt: "2026-09-02T10:05:00.000Z",
  },
  {
    id: "mock-following-04",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-02",
    text: "El cliente confirmó que su presupuesto máximo es de 4.5 millones.",
    contactSummary: "Prefiere colonias al norte de la ciudad.",
    nextAction: "Filtrar opciones dentro del presupuesto indicado.",
    attachments: [],
    createdAt: "2026-09-02T16:25:00.000Z",
  },
  {
    id: "mock-following-05",
    leadId: MOCK_LEAD_ID,
    authorType: "coordinator",
    authorId: "mock-coordinator-01",
    text: "Se enviaron referencias de cocina, jardín y recámara principal.",
    attachments: [
      mockImage("05a", "referencia-cocina.jpg"),
      mockImage("05b", "referencia-jardin.jpg"),
    ],
    createdAt: "2026-09-03T09:50:00.000Z",
  },
  {
    id: "mock-following-06",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "",
    attachments: [
      mockImage("06a", "plano-primer-nivel.jpg"),
      mockImage("06b", "plano-segundo-nivel.jpg"),
    ],
    createdAt: "2026-09-03T14:10:00.000Z",
  },
  {
    id: "mock-following-07",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "Llamada de seguimiento completada. Le gustó la ubicación de la propiedad en Montebello.",
    contactSummary: "Solicitó disponibilidad para visita durante el fin de semana.",
    nextAction: "Confirmar horario de visita para el sábado.",
    attachments: [],
    createdAt: "2026-09-04T11:30:00.000Z",
  },
  {
    id: "mock-following-08",
    leadId: MOCK_LEAD_ID,
    authorType: "coordinator",
    authorId: "mock-coordinator-01",
    text: "Se compartió la ubicación exacta y el acceso a la propiedad.",
    attachments: [mockImage("08", "ubicacion-propiedad.jpg")],
    createdAt: "2026-09-04T17:45:00.000Z",
  },
  {
    id: "mock-following-09",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-02",
    text: "",
    attachments: [mockImage("09", "recorrido-sala.jpg")],
    createdAt: "2026-09-05T08:20:00.000Z",
  },
  {
    id: "mock-following-10",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "La visita quedó agendada para el sábado a las 11:00 a. m.",
    contactSummary: "Asistirá con dos familiares.",
    nextAction: "Preparar ficha técnica impresa y opciones similares.",
    attachments: [],
    createdAt: "2026-09-05T13:35:00.000Z",
  },
  {
    id: "mock-following-11",
    leadId: MOCK_LEAD_ID,
    authorType: "coordinator",
    authorId: "mock-coordinator-01",
    text: "El cliente pidió comparar el área social con otra propiedad de la misma zona.",
    attachments: [mockImage("11", "area-social.jpg")],
    createdAt: "2026-09-06T10:10:00.000Z",
  },
  {
    id: "mock-following-12",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "",
    attachments: [
      mockImage("12a", "cochera.jpg"),
      mockImage("12b", "terraza.jpg"),
      mockImage("12c", "vista-jardin.jpg"),
    ],
    createdAt: "2026-09-06T15:40:00.000Z",
  },
  {
    id: "mock-following-13",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-02",
    text: "Después de la visita, el cliente indicó que le gustó la iluminación natural y el jardín.",
    contactSummary: "Tiene dudas sobre la forma de pago y gastos de escrituración.",
    nextAction: "Enviar desglose de gastos y alternativas de crédito.",
    attachments: [],
    createdAt: "2026-09-07T09:25:00.000Z",
  },
  {
    id: "mock-following-14",
    leadId: MOCK_LEAD_ID,
    authorType: "coordinator",
    authorId: "mock-coordinator-01",
    text: "Se mandó una simulación de crédito y el desglose estimado de gastos.",
    attachments: [mockImage("14", "simulacion-credito.jpg")],
    createdAt: "2026-09-07T12:15:00.000Z",
  },
  {
    id: "mock-following-15",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "",
    attachments: [mockImage("15", "documentos-propiedad.jpg")],
    createdAt: "2026-09-08T08:45:00.000Z",
  },
  {
    id: "mock-following-16",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "El cliente confirmó que revisará la simulación esta tarde y dará respuesta mañana.",
    nextAction: "Llamar mañana para conocer su decisión.",
    attachments: [],
    createdAt: "2026-09-08T11:55:00.000Z",
  },
  {
    id: "mock-following-17",
    leadId: MOCK_LEAD_ID,
    authorType: "coordinator",
    authorId: "mock-coordinator-01",
    text: "Se enviaron fotografías actualizadas de las áreas que solicitó revisar.",
    attachments: [
      mockImage("17a", "recamara-principal.jpg"),
      mockImage("17b", "bano-principal.jpg"),
    ],
    createdAt: "2026-09-08T16:05:00.000Z",
  },
  {
    id: "mock-following-18",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-02",
    text: "",
    attachments: [mockImage("18", "amenidades.jpg")],
    createdAt: "2026-09-07T09:10:00.000Z",
  },
  {
    id: "mock-following-19",
    leadId: MOCK_LEAD_ID,
    authorType: "agent",
    authorId: "mock-agent-01",
    text: "El cliente está interesado en avanzar, pero necesita validar la fecha de firma con su banco.",
    contactSummary: "No ha descartado la propiedad; mantiene alto interés.",
    nextAction: "Dar seguimiento al proceso de crédito el jueves.",
    attachments: [],
    createdAt: "2026-09-08T14:30:00.000Z",
  },
  {
    id: "mock-following-20",
    leadId: MOCK_LEAD_ID,
    authorType: "coordinator",
    authorId: "mock-coordinator-01",
    text: "Se compartió el expediente visual final de la propiedad.",
    attachments: [
      mockImage("20a", "expediente-fachada.jpg"),
      mockImage("20b", "expediente-interior.jpg"),
    ],
    createdAt: "2026-09-07T10:00:00.000Z",
  },
];
